export const certificationQuestions = [
  {
    id: 'certification-en-001',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer confirms the vehicle is running well. The agent then transfers without asking if the customer agrees to speak with a Service Advisor. What is the best evaluation?',
    options: [
      'Invalid. Vehicle confirmation is not transfer consent.',
      'Valid. Vehicle confirmation is enough consent.',
      'Valid only if the customer does not hang up.',
      'Valid because the Service Advisor can get consent later.',
    ],
    correct: 0,
    explanation: 'Certification rule: consent to transfer must be clear. A yes about vehicle condition is not permission to transfer.',
  },
  {
    id: 'certification-en-002',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'A customer asks, “Where did you get my information?” Which response is safest?',
    options: [
      'We work with vehicle-related records and dealership information to check possible coverage options.',
      'Your bank sent us your file.',
      'Your lender gave us your private information.',
      'The government sent us your vehicle record.',
    ],
    correct: 0,
    explanation: 'Do not claim the bank, lender, or government sent the file. Use safe vehicle/dealership-related wording.',
  },
  {
    id: 'certification-en-003',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The agent says, “This will take less than a minute,” to convince a busy customer to accept the transfer. What is the issue?',
    options: [
      'It is risky because it promises time and can mislead the customer.',
      'It is always the best rebuttal.',
      'It is okay as long as the agent sounds confident.',
      'It only matters if the customer complains.',
    ],
    correct: 0,
    explanation: 'Certification rule: do not train agents to use unsupported time promises.',
  },
  {
    id: 'certification-en-004',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer speaks English with the opener. After the Service Advisor says hello, the customer immediately asks for Spanish and no English conversation happens with the Service Advisor. How should this be treated?',
    options: [
      'Invalid English XFER.',
      'Valid English XFER.',
      'Valid because the opener spoke English.',
      'Valid if the agent waited 15 seconds in silence.',
    ],
    correct: 0,
    explanation: 'The English handoff did not actually start with the Service Advisor, so it should not be counted as a clean English XFER.',
  },
  {
    id: 'certification-en-005',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer speaks English with the Service Advisor for 20 seconds, then later asks for Spanish. How should this be treated?',
    options: [
      'Valid English XFER.',
      'Invalid because the customer eventually asked for Spanish.',
      'SPANIS only, no matter what happened before.',
      'DAIR because the language changed.',
    ],
    correct: 0,
    explanation: 'If the English conversation with the Service Advisor already happened long enough, the later Spanish request does not automatically invalidate it.',
  },
  {
    id: 'certification-en-006',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'A customer has a 2018 electric vehicle with low mileage. What should the agent understand?',
    options: [
      'It is not eligible because electric vehicles cannot be covered.',
      'It is eligible because the year and mileage are good.',
      'It is eligible if the customer agrees to transfer.',
      'The Service Advisor can always make an exception.',
    ],
    correct: 0,
    explanation: 'Electric vehicles are not eligible even if the year and mileage look good.',
  },
  {
    id: 'certification-en-007',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'A customer has a 2016 gas vehicle with 181,000 miles. It runs fine. What is the correct evaluation?',
    options: [
      'Not eligible because it is over 175,000 miles.',
      'Eligible because it runs fine.',
      'Eligible because it is newer than 2011.',
      'Eligible if the customer is interested.',
    ],
    correct: 0,
    explanation: 'Mileage over 175,000 makes it not eligible as a clean transfer.',
  },
  {
    id: 'certification-en-008',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The Service Advisor answers, but the agent speaks first and introduces the customer before the Service Advisor starts the handoff. What is the best rule?',
    options: [
      'The Service Advisor should speak first during the handoff.',
      'The opener should always speak first.',
      'It does not matter who speaks first.',
      'The customer should speak first before anyone else.',
    ],
    correct: 0,
    explanation: 'For a cleaner handoff, the Service Advisor should speak first, then the agent introduces the customer.',
  },
  {
    id: 'certification-en-009',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer hangs up during the 3-way call before speaking with the Service Advisor. What should the agent avoid doing?',
    options: [
      'Avoid counting it as a clean XFER.',
      'Mark it as XFER because the advisor was dialed.',
      'Leave the 3-way call and count it.',
      'Assume the customer was connected successfully.',
    ],
    correct: 0,
    explanation: 'Dialing the Service Advisor is not enough. The handoff must actually happen.',
  },
  {
    id: 'certification-en-010',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'A child answers and says their parent is not available. What is the correct agent action?',
    options: [
      'Do not transfer the child; the decision maker is not available.',
      'Transfer the child to the Service Advisor.',
      'Ask the child to approve the transfer.',
      'Mark it as XFER if the child stays on the line.',
    ],
    correct: 0,
    explanation: 'A child or non-decision maker should not be treated as a valid transfer.',
  },
  {
    id: 'certification-en-011',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says they are the co-signer but not the person who handles the vehicle decisions. What should the agent do?',
    options: [
      'Clarify who the decision maker is and try to speak with them before transferring.',
      'Transfer the co-signer as a clean XFER.',
      'Tell the co-signer they must decide now.',
      'Ignore the concern and continue the transfer.',
    ],
    correct: 0,
    explanation: 'Decision authority matters. The agent should clarify before moving forward.',
  },
  {
    id: 'certification-en-012',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says the check engine light is on and the car is not shifting correctly. What is the best action?',
    options: [
      'Clarify the issue and avoid treating it as a clean eligible transfer.',
      'Transfer anyway and hide the issue.',
      'Promise the advisor will cover the repair.',
      'Tell the customer current issues do not matter.',
    ],
    correct: 0,
    explanation: 'Current mechanical issues must be clarified and should not be pushed as clean eligible coverage.',
  },
  {
    id: 'certification-en-013',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I already have coverage and I am not interested.” What is the safest approach?',
    options: [
      'Acknowledge it, attempt a safe rebuttal, and do not transfer unless the customer clearly agrees.',
      'Transfer anyway because they answered the phone.',
      'Tell them their current coverage is bad.',
      'Say they must switch today.',
    ],
    correct: 0,
    explanation: 'Do not force a transfer from a clear rejection. Consent still matters.',
  },
  {
    id: 'certification-en-014',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “Stop calling me.” What disposition is most appropriate?',
    options: [
      'DNC - Do Not Call',
      'NI - Not Interested',
      'CALLBK - Callback',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'A clear request to stop calling should be dispositioned as DNC.',
  },
  {
    id: 'certification-en-015',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The line connects, there is background noise, but no person ever responds to the agent. What disposition fits best?',
    options: [
      'DAIR - Dead Air',
      'A - Answering Machine',
      'NI - Not Interested',
      'WN - Wrong Number',
    ],
    correct: 0,
    explanation: 'Use DAIR when the line connects but nobody actually speaks.',
  },
  {
    id: 'certification-en-016',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I am driving right now, call me later,” and refuses to continue. What disposition fits best?',
    options: [
      'CALLBK - Callback',
      'NI - Not Interested',
      'DNC - Do Not Call',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'If the customer cannot continue and asks for a later call, CALLBK is the best fit.',
  },
  {
    id: 'certification-en-017',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “Just send me the information.” What should the agent avoid?',
    options: [
      'Avoid promising documents, approval, price, or coverage that has not been reviewed.',
      'Promise to send paperwork after marking them approved.',
      'Say the advisor will lower the payment today.',
      'Skip consent and transfer immediately.',
    ],
    correct: 0,
    explanation: 'The safe path is to explain that the Service Advisor reviews what applies. Do not promise paperwork or approval.',
  },
  {
    id: 'certification-en-018',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'Which phrase should NOT be trained as the correct answer?',
    options: [
      'Your bank sent us your file.',
      'The Service Advisor can review the available options with you.',
      'I understand your concern.',
      'Would it be okay to connect you with the Service Advisor?',
    ],
    correct: 0,
    explanation: 'Do not say the bank sent the file.',
  },
  {
    id: 'certification-en-019',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'Which transfer has the best chance of being clean?',
    options: [
      'Customer gives clear consent, SA speaks first, agent introduces customer, and waits while both lines talk.',
      'Customer says the car runs fine and agent transfers without asking.',
      'Customer asks for callback and agent transfers anyway.',
      'Customer says wrong number and agent transfers anyway.',
    ],
    correct: 0,
    explanation: 'A clean transfer needs consent, proper SA handoff, and confirmed live connection.',
  },
  {
    id: 'certification-en-020',
    mode: 'certification',
    topic: 'certification',
    language: 'en',
    question_type: 'mc',
    question: 'The customer refuses the transfer clearly. What should the agent do?',
    options: [
      'Respect the refusal and disposition based on the customer response.',
      'Transfer silently.',
      'Put the customer on hold and dial the Service Advisor.',
      'Say the transfer is mandatory.',
    ],
    correct: 0,
    explanation: 'Certification rule: no transfer without consent.',
  },

  {
    id: 'certification-es-001',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente confirma que el vehículo funciona bien. Luego el agente transfiere sin preguntar si el cliente acepta hablar con un Service Advisor. ¿Cuál es la mejor evaluación?',
    options: [
      'Inválida. Confirmar el vehículo no es consentimiento para transferir.',
      'Válida. Confirmar el vehículo es suficiente consentimiento.',
      'Válida solo si el cliente no cuelga.',
      'Válida porque el Service Advisor puede obtener consentimiento después.',
    ],
    correct: 0,
    explanation: 'Regla de certificación: el consentimiento para transferir debe ser claro.',
  },
  {
    id: 'certification-es-002',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente pregunta: “¿De dónde sacaron mi información?” ¿Cuál respuesta es más segura?',
    options: [
      'Trabajamos con registros relacionados con vehículos e información de dealerships para revisar posibles opciones de cobertura.',
      'Su banco nos mandó su archivo.',
      'Su lender nos dio su información privada.',
      'El gobierno nos mandó su registro del vehículo.',
    ],
    correct: 0,
    explanation: 'No digas que el banco, lender o gobierno mandó el archivo.',
  },
  {
    id: 'certification-es-003',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El agente dice: “Esto tomará menos de un minuto,” para convencer a un cliente ocupado de aceptar la transferencia. ¿Cuál es el problema?',
    options: [
      'Es riesgoso porque promete tiempo y puede confundir al cliente.',
      'Siempre es el mejor rebuttal.',
      'Está bien si el agente suena seguro.',
      'Solo importa si el cliente se queja.',
    ],
    correct: 0,
    explanation: 'No se debe entrenar a los agentes a usar promesas de tiempo no aprobadas.',
  },
  {
    id: 'certification-es-004',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente habla inglés con el opener. Después de que el Service Advisor saluda, el cliente inmediatamente pide español y no hay conversación en inglés con el Service Advisor. ¿Cómo debe tratarse?',
    options: [
      'English XFER inválido.',
      'English XFER válido.',
      'Válido porque el opener habló inglés.',
      'Válido si el agente esperó 15 segundos en silencio.',
    ],
    correct: 0,
    explanation: 'El handoff en inglés no comenzó realmente con el Service Advisor.',
  },
  {
    id: 'certification-es-005',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente habla inglés con el Service Advisor por 20 segundos y luego pide español. ¿Cómo debe tratarse?',
    options: [
      'English XFER válido.',
      'Inválido porque después pidió español.',
      'SPANIS siempre, sin importar qué pasó antes.',
      'DAIR porque cambió el idioma.',
    ],
    correct: 0,
    explanation: 'Si la conversación en inglés con el Service Advisor ya ocurrió suficiente tiempo, pedir español después no lo invalida automáticamente.',
  },
  {
    id: 'certification-es-006',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'Un cliente tiene un vehículo eléctrico 2018 con poco millaje. ¿Qué debe entender el agente?',
    options: [
      'No es elegible porque los vehículos eléctricos no pueden ser cubiertos.',
      'Es elegible porque el año y millaje son buenos.',
      'Es elegible si el cliente acepta transferir.',
      'El Service Advisor siempre puede hacer una excepción.',
    ],
    correct: 0,
    explanation: 'Los vehículos eléctricos no son elegibles aunque el año y millaje parezcan buenos.',
  },
  {
    id: 'certification-es-007',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'Un cliente tiene un vehículo de gasolina 2016 con 181,000 millas. Funciona bien. ¿Cuál es la evaluación correcta?',
    options: [
      'No elegible porque está sobre 175,000 millas.',
      'Elegible porque funciona bien.',
      'Elegible porque es más nuevo que 2011.',
      'Elegible si el cliente está interesado.',
    ],
    correct: 0,
    explanation: 'Más de 175,000 millas lo hace no elegible como transferencia limpia.',
  },
  {
    id: 'certification-es-008',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El Service Advisor contesta, pero el agente habla primero y presenta al cliente antes de que el Service Advisor empiece el handoff. ¿Cuál es la mejor regla?',
    options: [
      'El Service Advisor debe hablar primero durante el handoff.',
      'El opener siempre debe hablar primero.',
      'No importa quién habla primero.',
      'El cliente debe hablar primero antes que todos.',
    ],
    correct: 0,
    explanation: 'Para un handoff más limpio, el Service Advisor debe hablar primero.',
  },
  {
    id: 'certification-es-009',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente cuelga durante la llamada de 3 vías antes de hablar con el Service Advisor. ¿Qué debe evitar el agente?',
    options: [
      'Evitar contarlo como XFER limpio.',
      'Marcar XFER porque se llamó al advisor.',
      'Salir de la llamada y contarlo.',
      'Asumir que el cliente quedó conectado bien.',
    ],
    correct: 0,
    explanation: 'Marcar al Service Advisor no es suficiente. El handoff debe pasar realmente.',
  },
  {
    id: 'certification-es-010',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'Un niño contesta y dice que su papá o mamá no está disponible. ¿Cuál es la acción correcta?',
    options: [
      'No transferir al niño; la persona que decide no está disponible.',
      'Transferir al niño con el Service Advisor.',
      'Pedirle al niño que apruebe la transferencia.',
      'Marcar XFER si el niño se queda en línea.',
    ],
    correct: 0,
    explanation: 'Un niño o persona que no decide no debe tratarse como transferencia válida.',
  },
  {
    id: 'certification-es-011',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice que es co-signer pero no la persona que maneja decisiones del vehículo. ¿Qué debe hacer el agente?',
    options: [
      'Aclarar quién decide y tratar de hablar con esa persona antes de transferir.',
      'Transferir al co-signer como XFER limpio.',
      'Decirle que debe decidir ahora.',
      'Ignorar la preocupación y continuar la transferencia.',
    ],
    correct: 0,
    explanation: 'La autoridad para decidir importa. El agente debe aclarar antes de avanzar.',
  },
  {
    id: 'certification-es-012',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice que la luz de check engine está prendida y el carro no está cambiando bien. ¿Cuál es la mejor acción?',
    options: [
      'Aclarar el problema y evitar tratarlo como transferencia limpia elegible.',
      'Transferir igual y ocultar el problema.',
      'Prometer que el advisor cubrirá la reparación.',
      'Decir que problemas actuales no importan.',
    ],
    correct: 0,
    explanation: 'Problemas mecánicos actuales deben aclararse y no deben empujarse como cobertura limpia.',
  },
  {
    id: 'certification-es-013',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Ya tengo cobertura y no estoy interesado.” ¿Cuál es el enfoque más seguro?',
    options: [
      'Reconocerlo, intentar un rebuttal seguro y no transferir a menos que el cliente acepte claramente.',
      'Transferir igual porque contestó el teléfono.',
      'Decirle que su cobertura actual es mala.',
      'Decirle que debe cambiarse hoy.',
    ],
    correct: 0,
    explanation: 'No fuerces una transferencia desde un rechazo claro.',
  },
  {
    id: 'certification-es-014',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “No me llamen más.” ¿Qué disposición corresponde mejor?',
    options: [
      'DNC - Do Not Call',
      'NI - Not Interested',
      'CALLBK - Callback',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'Una solicitud clara de no volver a llamar debe marcarse como DNC.',
  },
  {
    id: 'certification-es-015',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'La línea conecta, hay ruido de fondo, pero ninguna persona responde al agente. ¿Qué disposición corresponde mejor?',
    options: [
      'DAIR - Dead Air',
      'A - Answering Machine',
      'NI - Not Interested',
      'WN - Wrong Number',
    ],
    correct: 0,
    explanation: 'Usa DAIR cuando la línea conecta pero nadie habla.',
  },
  {
    id: 'certification-es-016',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Estoy manejando ahora, llámenme después,” y no quiere continuar. ¿Qué disposición corresponde mejor?',
    options: [
      'CALLBK - Callback',
      'NI - Not Interested',
      'DNC - Do Not Call',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'Si el cliente no puede continuar y pide llamada después, CALLBK es lo más correcto.',
  },
  {
    id: 'certification-es-017',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Solo mándeme la información.” ¿Qué debe evitar el agente?',
    options: [
      'Evitar prometer documentos, aprobación, precio o cobertura que no ha sido revisada.',
      'Prometer enviar papeles después de marcarlo aprobado.',
      'Decir que el advisor bajará el pago hoy.',
      'Saltar el consentimiento y transferir de inmediato.',
    ],
    correct: 0,
    explanation: 'Lo seguro es explicar que el Service Advisor revisa lo que aplica.',
  },
  {
    id: 'certification-es-018',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: '¿Qué frase NO debe entrenarse como respuesta correcta?',
    options: [
      'Su banco nos mandó su archivo.',
      'El Service Advisor puede revisar las opciones disponibles con usted.',
      'Entiendo su preocupación.',
      '¿Estaría bien conectarlo con el Service Advisor?',
    ],
    correct: 0,
    explanation: 'No se debe decir que el banco mandó el archivo.',
  },
  {
    id: 'certification-es-019',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: '¿Qué transferencia tiene más probabilidad de ser limpia?',
    options: [
      'El cliente da consentimiento claro, el SA habla primero, el agente presenta al cliente y espera mientras ambos hablan.',
      'El cliente dice que el carro funciona y el agente transfiere sin preguntar.',
      'El cliente pide callback y el agente transfiere igual.',
      'El cliente dice número equivocado y el agente transfiere igual.',
    ],
    correct: 0,
    explanation: 'Una transferencia limpia necesita consentimiento, handoff correcto y conexión viva confirmada.',
  },
  {
    id: 'certification-es-020',
    mode: 'certification',
    topic: 'certification',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente rechaza claramente la transferencia. ¿Qué debe hacer el agente?',
    options: [
      'Respetar el rechazo y dispositionar según la respuesta del cliente.',
      'Transferir en silencio.',
      'Poner al cliente en hold y llamar al Service Advisor.',
      'Decir que la transferencia es obligatoria.',
    ],
    correct: 0,
    explanation: 'Regla de certificación: no hay transferencia sin consentimiento.',
  },
]