export const disposeItQuestions = [
  {
    id: 'dispose-it-en-001',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The call goes straight to voicemail and the customer never answers live. What disposition should the agent use?',
    options: [
      'A - Answering Machine',
      'DAIR - Dead Air',
      'NI - Not Interested',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Use A when the call reaches voicemail or an answering machine.',
  },
  {
    id: 'dispose-it-en-002',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The line connects, but nobody speaks at all. The agent never gets a response from anyone on the line. What disposition fits best?',
    options: [
      'DAIR - Dead Air',
      'A - Answering Machine',
      'NI - Not Interested',
      'WN - Wrong Number',
    ],
    correct: 0,
    explanation: 'Use DAIR when the line connects but nobody responds at all.',
  },
  {
    id: 'dispose-it-en-003',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “Stop calling me. Remove me from your list.” What disposition should be used?',
    options: [
      'DNC - Do Not Call',
      'NI - Not Interested',
      'CALLBK - Callback',
      'A - Answering Machine',
    ],
    correct: 0,
    explanation: 'Use DNC when the customer clearly asks not to be called again.',
  },
  {
    id: 'dispose-it-en-004',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer hears the purpose of the call and says they are not interested, then refuses to continue. What disposition fits best?',
    options: [
      'NI - Not Interested',
      'CALLBK - Callback',
      'DNC - Do Not Call',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'Use NI when the customer is not interested and does not continue.',
  },
  {
    id: 'dispose-it-en-005',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says they are busy. The agent tries to continue, but the customer still refuses and asks to be called later. What disposition should be used?',
    options: [
      'CALLBK - Callback',
      'NI - Not Interested',
      'DAIR - Dead Air',
      'A - Answering Machine',
    ],
    correct: 0,
    explanation: 'Use CALLBK when the customer is busy and the correct next action is a callback.',
  },
  {
    id: 'dispose-it-en-006',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The person who answers says, “You have the wrong number. I do not know that person.” What disposition fits best?',
    options: [
      'WN - Wrong Number',
      'WRNGVE - Wrong Vehicle',
      'NI - Not Interested',
      'DNC - Do Not Call',
    ],
    correct: 0,
    explanation: 'Use WN when the phone number or person is wrong.',
  },
  {
    id: 'dispose-it-en-007',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says the vehicle on file is not their vehicle. The name and number may be correct, but the vehicle is wrong. What disposition should be used?',
    options: [
      'WRNGVE - Wrong Vehicle',
      'WN - Wrong Number',
      'NI - Not Interested',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Use WRNGVE when the vehicle information on file is wrong.',
  },
  {
    id: 'dispose-it-en-008',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer asks for Spanish, but the agent does not speak Spanish and no direct Spanish Service Advisor transfer is completed. What disposition fits best?',
    options: [
      'SPANIS - Spanish Needed',
      'SPXFER - Spanish Transfer',
      'XFER - English Transfer',
      'NI - Not Interested',
    ],
    correct: 0,
    explanation: 'Use SPANIS when the customer needs Spanish but there is no completed Spanish transfer.',
  },
  {
    id: 'dispose-it-en-009',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer requests Spanish and is directly transferred to a Spanish Service Advisor. What disposition should be used?',
    options: [
      'SPXFER - Spanish Transfer',
      'SPANIS - Spanish Needed',
      'XFER - English Transfer',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Use SPXFER when the customer is transferred to a Spanish Service Advisor.',
  },
  {
    id: 'dispose-it-en-010',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer gives consent, the Service Advisor answers, the handoff is completed correctly, and the customer stays connected. What disposition fits best?',
    options: [
      'XFER - English Transfer',
      'SPXFER - Spanish Transfer',
      'CALLBK - Callback',
      'NI - Not Interested',
    ],
    correct: 0,
    explanation: 'Use XFER for a clean English transfer after proper consent and handoff.',
  },
  {
    id: 'dispose-it-en-011',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer curses at the agent and threatens legal action if they call again. What disposition should the agent choose?',
    options: [
      'DNC - Do Not Call',
      'NI - Not Interested',
      'A - Answering Machine',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Use DNC when the customer clearly demands no more calls or threatens legal action.',
  },
  {
    id: 'dispose-it-en-012',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer answers, listens for a few seconds, says “No thanks,” and hangs up. What disposition should be used?',
    options: [
      'NI - Not Interested',
      'A - Answering Machine',
      'DAIR - Dead Air',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Use NI when the customer rejects the call after hearing the purpose.',
  },
  {
    id: 'dispose-it-en-013',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The call connects and there is background noise, but no person ever responds to the agent. What disposition fits best?',
    options: [
      'DAIR - Dead Air',
      'NI - Not Interested',
      'A - Answering Machine',
      'WN - Wrong Number',
    ],
    correct: 0,
    explanation: 'Use DAIR when nobody actually speaks to the agent after the line connects.',
  },
  {
    id: 'dispose-it-en-014',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I am driving right now, call me later,” and does not want to continue the call. What disposition should be used?',
    options: [
      'CALLBK - Callback',
      'NI - Not Interested',
      'DNC - Do Not Call',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'Use CALLBK when the customer cannot continue now and the next action is to call back later.',
  },
  {
    id: 'dispose-it-en-015',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I only speak Spanish,” and the agent routes the call directly to a Spanish Service Advisor. What disposition fits best?',
    options: [
      'SPXFER - Spanish Transfer',
      'SPANIS - Spanish Needed',
      'NI - Not Interested',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Use SPXFER when the Spanish handoff is actually completed.',
  },
  {
    id: 'dispose-it-en-016',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer confirms the vehicle, agrees to hear options, but asks the Service Advisor to call them back before any real conversation starts. What disposition fits best?',
    options: [
      'CALLBK - Callback',
      'XFER - English Transfer',
      'NI - Not Interested',
      'DAIR - Dead Air',
    ],
    correct: 0,
    explanation: 'Use CALLBK if the customer does not complete the live conversation and asks for a callback.',
  },
  {
    id: 'dispose-it-en-017',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The agent reaches a voicemail greeting that says the customer is unavailable. What disposition should be used?',
    options: [
      'A - Answering Machine',
      'DAIR - Dead Air',
      'CALLBK - Callback',
      'WN - Wrong Number',
    ],
    correct: 0,
    explanation: 'Voicemail or answering machine should be dispositioned as A.',
  },
  {
    id: 'dispose-it-en-018',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says they sold the vehicle and no longer own it. What disposition fits best?',
    options: [
      'WRNGVE - Wrong Vehicle',
      'WN - Wrong Number',
      'NI - Not Interested',
      'DNC - Do Not Call',
    ],
    correct: 0,
    explanation: 'Use WRNGVE when the vehicle information is no longer correct for the customer.',
  },
  {
    id: 'dispose-it-en-019',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer gives consent and is connected to an English Service Advisor, but the agent never hears the Service Advisor speak. What disposition should not be used?',
    options: [
      'XFER - English Transfer',
      'DAIR - Dead Air',
      'CALLBK - Callback',
      'NI - Not Interested',
    ],
    correct: 0,
    explanation: 'Do not use XFER if the handoff was not actually completed with the Service Advisor speaking.',
  },
  {
    id: 'dispose-it-en-020',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “This is my car, but I am not interested in any coverage.” They refuse to continue. What disposition fits best?',
    options: [
      'NI - Not Interested',
      'WRNGVE - Wrong Vehicle',
      'CALLBK - Callback',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'Use NI when the customer is the right person/vehicle but refuses the offer.',
  },

  {
    id: 'dispose-it-es-001',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'La llamada cae directamente en voicemail y el cliente nunca contesta en vivo. ¿Qué disposición debe usar el agente?',
    options: [
      'A - Answering Machine',
      'DAIR - Dead Air',
      'NI - Not Interested',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Usa A cuando la llamada cae en voicemail o máquina contestadora.',
  },
  {
    id: 'dispose-it-es-002',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'La línea conecta, pero nadie habla. El agente nunca recibe respuesta de nadie en la línea. ¿Qué disposición corresponde?',
    options: [
      'DAIR - Dead Air',
      'A - Answering Machine',
      'NI - Not Interested',
      'WN - Wrong Number',
    ],
    correct: 0,
    explanation: 'Usa DAIR cuando la línea conecta pero nadie responde.',
  },
  {
    id: 'dispose-it-es-003',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “No me llamen más. Sáquenme de la lista.” ¿Qué disposición debe usarse?',
    options: [
      'DNC - Do Not Call',
      'NI - Not Interested',
      'CALLBK - Callback',
      'A - Answering Machine',
    ],
    correct: 0,
    explanation: 'Usa DNC cuando el cliente pide claramente que no lo vuelvan a llamar.',
  },
  {
    id: 'dispose-it-es-004',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente escucha el propósito de la llamada y dice que no está interesado, luego se niega a continuar. ¿Qué disposición corresponde?',
    options: [
      'NI - Not Interested',
      'CALLBK - Callback',
      'DNC - Do Not Call',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'Usa NI cuando el cliente no está interesado y no continúa.',
  },
  {
    id: 'dispose-it-es-005',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice que está ocupado. El agente intenta continuar, pero el cliente insiste en que lo llamen después. ¿Qué disposición debe usarse?',
    options: [
      'CALLBK - Callback',
      'NI - Not Interested',
      'DAIR - Dead Air',
      'A - Answering Machine',
    ],
    correct: 0,
    explanation: 'Usa CALLBK cuando el cliente está ocupado y la acción correcta es llamar después.',
  },
  {
    id: 'dispose-it-es-006',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'La persona que contesta dice: “Número equivocado. No conozco a esa persona.” ¿Qué disposición corresponde?',
    options: [
      'WN - Wrong Number',
      'WRNGVE - Wrong Vehicle',
      'NI - Not Interested',
      'DNC - Do Not Call',
    ],
    correct: 0,
    explanation: 'Usa WN cuando el número o la persona son incorrectos.',
  },
  {
    id: 'dispose-it-es-007',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice que el vehículo en el archivo no es su vehículo. El nombre y número pueden estar correctos, pero el vehículo está mal. ¿Qué disposición debe usarse?',
    options: [
      'WRNGVE - Wrong Vehicle',
      'WN - Wrong Number',
      'NI - Not Interested',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Usa WRNGVE cuando la información del vehículo en el archivo está incorrecta.',
  },
  {
    id: 'dispose-it-es-008',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente pide español, pero el agente no habla español y no se completa una transferencia directa con un Service Advisor en español. ¿Qué disposición corresponde?',
    options: [
      'SPANIS - Spanish Needed',
      'SPXFER - Spanish Transfer',
      'XFER - English Transfer',
      'NI - Not Interested',
    ],
    correct: 0,
    explanation: 'Usa SPANIS cuando el cliente necesita español pero no se completa una transferencia en español.',
  },
  {
    id: 'dispose-it-es-009',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente pide español y es transferido directamente con un Service Advisor en español. ¿Qué disposición debe usarse?',
    options: [
      'SPXFER - Spanish Transfer',
      'SPANIS - Spanish Needed',
      'XFER - English Transfer',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Usa SPXFER cuando el cliente es transferido con un Service Advisor en español.',
  },
  {
    id: 'dispose-it-es-010',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente da consentimiento, el Service Advisor contesta, el handoff se completa correctamente y el cliente queda conectado. ¿Qué disposición corresponde?',
    options: [
      'XFER - English Transfer',
      'SPXFER - Spanish Transfer',
      'CALLBK - Callback',
      'NI - Not Interested',
    ],
    correct: 0,
    explanation: 'Usa XFER para una transferencia limpia en inglés después de consentimiento y handoff correcto.',
  },
  {
    id: 'dispose-it-es-011',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente insulta al agente y amenaza con acciones legales si vuelven a llamar. ¿Qué disposición debe escoger el agente?',
    options: [
      'DNC - Do Not Call',
      'NI - Not Interested',
      'A - Answering Machine',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Usa DNC cuando el cliente exige que no lo llamen más o amenaza con acciones legales.',
  },
  {
    id: 'dispose-it-es-012',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente contesta, escucha unos segundos, dice “No gracias” y cuelga. ¿Qué disposición debe usarse?',
    options: [
      'NI - Not Interested',
      'A - Answering Machine',
      'DAIR - Dead Air',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Usa NI cuando el cliente rechaza la llamada después de escuchar el propósito.',
  },
  {
    id: 'dispose-it-es-013',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'La llamada conecta y hay ruido de fondo, pero ninguna persona responde al agente. ¿Qué disposición corresponde?',
    options: [
      'DAIR - Dead Air',
      'NI - Not Interested',
      'A - Answering Machine',
      'WN - Wrong Number',
    ],
    correct: 0,
    explanation: 'Usa DAIR cuando nadie habla con el agente después de que la línea conecta.',
  },
  {
    id: 'dispose-it-es-014',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Estoy manejando ahora, llámenme después,” y no quiere continuar la llamada. ¿Qué disposición debe usarse?',
    options: [
      'CALLBK - Callback',
      'NI - Not Interested',
      'DNC - Do Not Call',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'Usa CALLBK cuando el cliente no puede continuar ahora y la acción correcta es llamar luego.',
  },
  {
    id: 'dispose-it-es-015',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Solo hablo español,” y el agente pasa la llamada directamente a un Service Advisor en español. ¿Qué disposición corresponde?',
    options: [
      'SPXFER - Spanish Transfer',
      'SPANIS - Spanish Needed',
      'NI - Not Interested',
      'CALLBK - Callback',
    ],
    correct: 0,
    explanation: 'Usa SPXFER cuando el handoff en español sí se completa.',
  },
  {
    id: 'dispose-it-es-016',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente confirma el vehículo, acepta escuchar opciones, pero le pide al Service Advisor que lo llame después antes de que empiece una conversación real. ¿Qué disposición corresponde?',
    options: [
      'CALLBK - Callback',
      'XFER - English Transfer',
      'NI - Not Interested',
      'DAIR - Dead Air',
    ],
    correct: 0,
    explanation: 'Usa CALLBK si el cliente no completa la conversación en vivo y pide que lo llamen luego.',
  },
  {
    id: 'dispose-it-es-017',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El agente llega a un mensaje de voicemail que dice que el cliente no está disponible. ¿Qué disposición debe usarse?',
    options: [
      'A - Answering Machine',
      'DAIR - Dead Air',
      'CALLBK - Callback',
      'WN - Wrong Number',
    ],
    correct: 0,
    explanation: 'Voicemail o máquina contestadora debe marcarse como A.',
  },
  {
    id: 'dispose-it-es-018',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice que vendió el vehículo y ya no lo tiene. ¿Qué disposición corresponde?',
    options: [
      'WRNGVE - Wrong Vehicle',
      'WN - Wrong Number',
      'NI - Not Interested',
      'DNC - Do Not Call',
    ],
    correct: 0,
    explanation: 'Usa WRNGVE cuando la información del vehículo ya no corresponde al cliente.',
  },
  {
    id: 'dispose-it-es-019',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente da consentimiento y es conectado con un Service Advisor en inglés, pero el agente nunca escucha al Service Advisor hablar. ¿Qué disposición NO debe usarse?',
    options: [
      'XFER - English Transfer',
      'DAIR - Dead Air',
      'CALLBK - Callback',
      'NI - Not Interested',
    ],
    correct: 0,
    explanation: 'No uses XFER si el handoff no se completó realmente con el Service Advisor hablando.',
  },
  {
    id: 'dispose-it-es-020',
    mode: 'disposition-trainer',
    topic: 'disposeit',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Sí es mi carro, pero no estoy interesado en ninguna cobertura.” Se niega a continuar. ¿Qué disposición corresponde?',
    options: [
      'NI - Not Interested',
      'WRNGVE - Wrong Vehicle',
      'CALLBK - Callback',
      'XFER - English Transfer',
    ],
    correct: 0,
    explanation: 'Usa NI cuando es la persona/vehículo correcto, pero rechaza la oferta.',
  },
]