export const eligibleQuestions = [
  {
    id: 'eligible-en-001',
    mode: 'eligible',
    topic: 'eligible',
    language: 'en',
    question_type: 'binary',
    question: 'A customer has a 2019 gas SUV with 68,000 miles. The vehicle runs fine and has no current mechanical issues. Eligible or not eligible?',
    options: ['Eligible', 'Not eligible'],
    correct: 0,
    explanation: 'This is eligible: newer than 2011, under the mileage limit, gas vehicle, and in good running condition.',
  },
  {
    id: 'eligible-en-002',
    mode: 'eligible',
    topic: 'eligible',
    language: 'en',
    question_type: 'binary',
    question: 'A customer has a 2010 sedan with 120,000 miles. The car runs fine. Eligible or not eligible?',
    options: ['Eligible', 'Not eligible'],
    correct: 1,
    explanation: 'Not eligible. Vehicles before 2011 cannot be covered.',
  },
  {
    id: 'eligible-en-003',
    mode: 'eligible',
    topic: 'eligible',
    language: 'en',
    question_type: 'binary',
    question: 'A customer has a 2018 electric vehicle with 45,000 miles. Eligible or not eligible?',
    options: ['Eligible', 'Not eligible'],
    correct: 1,
    explanation: 'Not eligible. Electric vehicles cannot be covered.',
  },
  {
    id: 'eligible-en-004',
    mode: 'eligible',
    topic: 'eligible',
    language: 'en',
    question_type: 'binary',
    question: 'A customer has a 2016 gas vehicle with 181,000 miles. It still runs fine. Eligible or not eligible?',
    options: ['Eligible', 'Not eligible'],
    correct: 1,
    explanation: 'Not eligible. Vehicles over 175,000 miles cannot be covered.',
  },
  {
    id: 'eligible-en-005',
    mode: 'eligible',
    topic: 'eligible',
    language: 'en',
    question_type: 'binary',
    question: 'A customer has a 2020 gas vehicle with 80,000 miles, but the check engine light is on and the car is not shifting properly. Eligible or not eligible?',
    options: ['Eligible', 'Not eligible'],
    correct: 1,
    explanation: 'Not eligible as a clean transfer. Current mechanical issues must not be treated as clean eligible coverage.',
  },
  {
    id: 'eligible-en-006',
    mode: 'eligible',
    topic: 'eligible',
    language: 'en',
    question_type: 'binary',
    question: 'A customer has a 2017 pickup truck with 95,000 miles. It is currently running and has no warning lights. Eligible or not eligible?',
    options: ['Eligible', 'Not eligible'],
    correct: 0,
    explanation: 'Eligible. It is 2011 or newer, under 175,000 miles, and in good running condition.',
  },
  {
    id: 'eligible-en-007',
    mode: 'eligible',
    topic: 'eligible',
    language: 'en',
    question_type: 'binary',
    question: 'A customer has a motorcycle and asks if it can be covered. Eligible or not eligible?',
    options: ['Eligible', 'Not eligible'],
    correct: 1,
    explanation: 'Not eligible. Motorcycles are not eligible for this coverage.',
  },
  {
    id: 'eligible-en-008',
    mode: 'eligible',
    topic: 'eligible',
    language: 'en',
    question_type: 'binary',
    question: 'A customer has a 2021 gas car with 50,000 miles, but it is missing a tire and cannot currently be driven. Eligible or not eligible?',
    options: ['Eligible', 'Not eligible'],
    correct: 1,
    explanation: 'Not eligible as a clean transfer. The vehicle must be in good running condition.',
  },

  {
    id: 'eligible-es-001',
    mode: 'eligible',
    topic: 'eligible',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente tiene una SUV de gasolina 2019 con 68,000 millas. El vehículo funciona bien y no tiene problemas mecánicos actuales. ¿Elegible o no elegible?',
    options: ['Elegible', 'No elegible'],
    correct: 0,
    explanation: 'Elegible. Es 2011 o más nuevo, está debajo del límite de millas, no es eléctrico y funciona bien.',
  },
  {
    id: 'eligible-es-002',
    mode: 'eligible',
    topic: 'eligible',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente tiene un sedán 2010 con 120,000 millas. El carro funciona bien. ¿Elegible o no elegible?',
    options: ['Elegible', 'No elegible'],
    correct: 1,
    explanation: 'No elegible. Vehículos antes de 2011 no pueden ser cubiertos.',
  },
  {
    id: 'eligible-es-003',
    mode: 'eligible',
    topic: 'eligible',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente tiene un vehículo eléctrico 2018 con 45,000 millas. ¿Elegible o no elegible?',
    options: ['Elegible', 'No elegible'],
    correct: 1,
    explanation: 'No elegible. Vehículos eléctricos no pueden ser cubiertos.',
  },
  {
    id: 'eligible-es-004',
    mode: 'eligible',
    topic: 'eligible',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente tiene un vehículo de gasolina 2016 con 181,000 millas. Todavía funciona bien. ¿Elegible o no elegible?',
    options: ['Elegible', 'No elegible'],
    correct: 1,
    explanation: 'No elegible. Vehículos con más de 175,000 millas no pueden ser cubiertos.',
  },
  {
    id: 'eligible-es-005',
    mode: 'eligible',
    topic: 'eligible',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente tiene un vehículo de gasolina 2020 con 80,000 millas, pero tiene la luz de check engine prendida y no cambia bien. ¿Elegible o no elegible?',
    options: ['Elegible', 'No elegible'],
    correct: 1,
    explanation: 'No elegible como transferencia limpia. Problemas mecánicos actuales no deben tratarse como elegibles limpios.',
  },
  {
    id: 'eligible-es-006',
    mode: 'eligible',
    topic: 'eligible',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente tiene una pickup 2017 con 95,000 millas. Está funcionando y no tiene luces de advertencia. ¿Elegible o no elegible?',
    options: ['Elegible', 'No elegible'],
    correct: 0,
    explanation: 'Elegible. Es 2011 o más nueva, está debajo de 175,000 millas y funciona bien.',
  },
  {
    id: 'eligible-es-007',
    mode: 'eligible',
    topic: 'eligible',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente tiene una motocicleta y pregunta si puede ser cubierta. ¿Elegible o no elegible?',
    options: ['Elegible', 'No elegible'],
    correct: 1,
    explanation: 'No elegible. Motocicletas no aplican para esta cobertura.',
  },
  {
    id: 'eligible-es-008',
    mode: 'eligible',
    topic: 'eligible',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente tiene un carro de gasolina 2021 con 50,000 millas, pero le falta una llanta y no se puede manejar actualmente. ¿Elegible o no elegible?',
    options: ['Elegible', 'No elegible'],
    correct: 1,
    explanation: 'No elegible como transferencia limpia. El vehículo debe estar en buena condición para manejar.',
  },
]