export const objectionBattleQuestions = [
  {
    id: 'objection-battle-en-001',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I am not interested.” What is the best response before ending the call?',
    options: [
      'I understand. Just so I do not waste your time, this is only to see if there may be updated options for your vehicle before you decide.',
      'Okay, I will transfer you anyway so the advisor can convince you.',
      'You have to listen because this is required.',
      'This will take less than a minute, I promise.',
    ],
    correct: 0,
    explanation: 'A good rebuttal acknowledges the customer, keeps control, and avoids pressure or false promises.',
  },
  {
    id: 'objection-battle-en-002',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “How much does it cost?” What is the safest response?',
    options: [
      'That depends on the available options, and the Service Advisor can review that with you before you decide.',
      'It is free today.',
      'Your payment will be lower for sure.',
      'I do not know, but I will transfer you anyway.',
    ],
    correct: 0,
    explanation: 'Do not promise price, discounts, or lower payments. Bridge the question to the Service Advisor.',
  },
  {
    id: 'objection-battle-en-003',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I already have coverage.” What is the best response?',
    options: [
      'That is good. This would just let the Service Advisor check if there are any updated options or gaps before you make a decision.',
      'Then your current coverage is probably bad.',
      'You need to cancel it and switch today.',
      'That does not matter, I am transferring you.',
    ],
    correct: 0,
    explanation: 'Acknowledge existing coverage and position the handoff as a review, not a forced replacement.',
  },
  {
    id: 'objection-battle-en-004',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “Where did you get my information?” What is the safest response?',
    options: [
      'We work with vehicle-related records and dealership information to check possible coverage options for your vehicle.',
      'Your bank sent us your private file.',
      'I cannot tell you that.',
      'The government gave us your information.',
    ],
    correct: 0,
    explanation: 'Use general approved language. Do not claim the bank, lender, or government sent the file.',
  },
  {
    id: 'objection-battle-en-005',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “Is this a scam?” What is the best response?',
    options: [
      'I understand your concern. I am only verifying the vehicle information and, if you agree, connecting you with a Service Advisor to explain the options.',
      'No, stop asking questions.',
      'It is definitely not a scam because I said so.',
      'Your bank told us to call you.',
    ],
    correct: 0,
    explanation: 'Stay calm, explain the purpose, and avoid unsupported claims.',
  },
  {
    id: 'objection-battle-en-006',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I am busy.” What is the strongest safe response?',
    options: [
      'I understand. Before I let you go, would it be okay to quickly connect you with the Service Advisor so they can explain the options, or is a later time better?',
      'It will be less than a minute, I promise.',
      'You need to stay on the phone.',
      'I will transfer you even if you are busy.',
    ],
    correct: 0,
    explanation: 'Acknowledge the timing, ask for permission, and do not use fake time promises.',
  },
  {
    id: 'objection-battle-en-007',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “Just send me the information.” What is the best response?',
    options: [
      'The Service Advisor would need to review the options with you directly so you know what applies before anything is sent.',
      'Sure, I will send it, but I need to transfer you first without explaining.',
      'We cannot send anything ever.',
      'I will mark you as approved and send paperwork.',
    ],
    correct: 0,
    explanation: 'Do not promise paperwork or approval. Explain that the advisor must review what applies.',
  },
  {
    id: 'objection-battle-en-008',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I do not make decisions. My spouse handles this.” What is the best response?',
    options: [
      'No problem. Is your spouse available now so the Service Advisor can review the options with the decision maker?',
      'You can decide for them anyway.',
      'I will transfer you even though you cannot make the decision.',
      'That is okay, I will put the coverage under your name.',
    ],
    correct: 0,
    explanation: 'The decision maker should be involved before moving forward.',
  },
  {
    id: 'objection-battle-en-009',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “My car is fine, I do not need anything.” What is the best response?',
    options: [
      'That is good to hear. This is usually reviewed while the vehicle is still running well, so the advisor can explain what options may be available.',
      'If it is fine, then you must buy coverage now.',
      'It will break soon for sure.',
      'Then I will transfer you without asking.',
    ],
    correct: 0,
    explanation: 'Use the vehicle condition as a reason to review options, without fear tactics or pressure.',
  },
  {
    id: 'objection-battle-en-010',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I cannot afford anything right now.” What is the safest response?',
    options: [
      'I understand. The Service Advisor can review what options are available, and you can decide if anything makes sense for you.',
      'Do not worry, it will be free.',
      'They will lower your payment today.',
      'You have to pay today to stay protected.',
    ],
    correct: 0,
    explanation: 'Do not promise free coverage, lower payments, or payment requirements.',
  },
  {
    id: 'objection-battle-en-011',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I need to talk to my husband/wife first.” What is the best response?',
    options: [
      'Of course. Are they available now? That way the Service Advisor can explain the options to both of you at the same time.',
      'You do not need them.',
      'Just say yes and tell them later.',
      'I will transfer you and you can figure it out after.',
    ],
    correct: 0,
    explanation: 'Respect the decision process and try to include the other decision maker if available.',
  },
  {
    id: 'objection-battle-en-012',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I am at work.” What is the best response?',
    options: [
      'I understand. Would now still be okay for a quick connection with the Service Advisor, or would a callback be better?',
      'Your job can wait.',
      'This is mandatory, so stay on the line.',
      'I promise it will be under one minute.',
    ],
    correct: 0,
    explanation: 'Give the customer a professional option without forcing or promising time.',
  },
  {
    id: 'objection-battle-en-013',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I do not remember requesting this.” What is the safest response?',
    options: [
      'That is okay. I am just verifying the vehicle information and checking if there are options available for you to review.',
      'You definitely requested it, so you have to continue.',
      'Your lender requested it for you.',
      'It does not matter whether you requested it.',
    ],
    correct: 0,
    explanation: 'Stay neutral and explain the purpose. Do not argue or invent a source.',
  },
  {
    id: 'objection-battle-en-014',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “Can you just tell me the company name?” What is the best response?',
    options: [
      'I can explain the purpose of the call, and the Service Advisor can go over the program details with you directly.',
      'I cannot tell you anything.',
      'It is from your bank.',
      'The company name does not matter.',
    ],
    correct: 0,
    explanation: 'Be transparent about the call purpose without making unsupported claims.',
  },
  {
    id: 'objection-battle-en-015',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I only want to know if I qualify.” What is the best response?',
    options: [
      'That is exactly what the Service Advisor can help review after I verify the vehicle and connect you with them.',
      'You already qualify for everything.',
      'You cannot qualify unless you pay today.',
      'I will mark you approved without checking.',
    ],
    correct: 0,
    explanation: 'Do not guarantee eligibility. Use the Service Advisor for review.',
  },
  {
    id: 'objection-battle-en-016',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I am not the owner, I only co-signed.” What should the agent do?',
    options: [
      'Clarify who the decision maker or current owner is and try to speak with that person before any transfer.',
      'Transfer the co-signer anyway as a valid XFER.',
      'Tell them they are responsible and must continue.',
      'Ignore that and keep reading the script.',
    ],
    correct: 0,
    explanation: 'The agent should clarify decision authority before transferring.',
  },
  {
    id: 'objection-battle-en-017',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “My check engine light is on.” What is the safest response?',
    options: [
      'Clarify the current condition of the vehicle before moving forward, because current mechanical issues may affect eligibility.',
      'Transfer them anyway and hide that detail.',
      'Say it does not matter.',
      'Tell them the advisor will cover the repair today.',
    ],
    correct: 0,
    explanation: 'Current mechanical issues need clarification. Do not promise coverage for existing problems.',
  },
  {
    id: 'objection-battle-en-018',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I have over 180,000 miles.” What is the best agent action?',
    options: [
      'Do not push a clean transfer; clarify eligibility because the mileage is over the limit.',
      'Transfer them anyway because mileage does not matter.',
      'Tell them they are approved.',
      'Say the Service Advisor will ignore the mileage.',
    ],
    correct: 0,
    explanation: 'Over 175,000 miles is not eligible, so it should not be pushed as a clean transfer.',
  },
  {
    id: 'objection-battle-en-019',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I have an electric vehicle.” What is the best response?',
    options: [
      'Clarify and avoid pushing it as eligible, because electric vehicles cannot be covered.',
      'Transfer them anyway.',
      'Tell them electric vehicles are always covered.',
      'Say the advisor will make an exception.',
    ],
    correct: 0,
    explanation: 'Electric vehicles cannot be covered, so the agent should not push it as eligible.',
  },
  {
    id: 'objection-battle-en-020',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'en',
    question_type: 'mc',
    question: 'The customer says, “I do not want to be transferred.” What should the agent do?',
    options: [
      'Respect that, avoid forcing the transfer, and disposition the call based on the customer response.',
      'Transfer them silently.',
      'Tell them they have no choice.',
      'Put them on hold and dial anyway.',
    ],
    correct: 0,
    explanation: 'A transfer needs consent. If the customer refuses, do not force it.',
  },

  {
    id: 'objection-battle-es-001',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “No estoy interesado.” ¿Cuál es la mejor respuesta antes de terminar la llamada?',
    options: [
      'Lo entiendo. Para no hacerle perder tiempo, esto es solo para revisar si puede haber opciones actualizadas para su vehículo antes de que usted decida.',
      'Está bien, igual lo voy a transferir para que el advisor lo convenza.',
      'Tiene que escuchar porque esto es obligatorio.',
      'Esto tomará menos de un minuto, se lo prometo.',
    ],
    correct: 0,
    explanation: 'Un buen rebuttal reconoce al cliente, mantiene control y evita presión o promesas falsas.',
  },
  {
    id: 'objection-battle-es-002',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “¿Cuánto cuesta?” ¿Cuál es la respuesta más segura?',
    options: [
      'Eso depende de las opciones disponibles, y el Service Advisor puede revisarlo con usted antes de que tome una decisión.',
      'Es gratis hoy.',
      'Su pago va a bajar seguro.',
      'No sé, pero igual lo voy a transferir.',
    ],
    correct: 0,
    explanation: 'No prometas precio, descuentos ni pagos más bajos. Lleva la pregunta al Service Advisor.',
  },
  {
    id: 'objection-battle-es-003',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Ya tengo cobertura.” ¿Cuál es la mejor respuesta?',
    options: [
      'Perfecto. Esto solo permitiría que el Service Advisor revise si hay opciones actualizadas o algún espacio en su cobertura actual antes de que usted decida.',
      'Entonces su cobertura actual seguramente es mala.',
      'Tiene que cancelarla y cambiarse hoy.',
      'Eso no importa, lo voy a transferir.',
    ],
    correct: 0,
    explanation: 'Reconoce la cobertura existente y presenta el handoff como revisión, no como reemplazo forzado.',
  },
  {
    id: 'objection-battle-es-004',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente pregunta: “¿De dónde sacaron mi información?” ¿Cuál es la respuesta más segura?',
    options: [
      'Trabajamos con registros relacionados con vehículos e información de dealerships para revisar posibles opciones de cobertura para su vehículo.',
      'Su banco nos mandó su archivo privado.',
      'No puedo decirle eso.',
      'El gobierno nos dio su información.',
    ],
    correct: 0,
    explanation: 'Usa lenguaje general y seguro. No digas que el banco, lender o gobierno envió el archivo.',
  },
  {
    id: 'objection-battle-es-005',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “¿Esto es una estafa?” ¿Cuál es la mejor respuesta?',
    options: [
      'Entiendo su preocupación. Solo estoy verificando la información del vehículo y, si usted está de acuerdo, lo conecto con un Service Advisor para explicar las opciones.',
      'No, deje de preguntar.',
      'No es estafa porque yo lo digo.',
      'Su banco nos dijo que lo llamáramos.',
    ],
    correct: 0,
    explanation: 'Mantén la calma, explica el propósito y evita afirmaciones no aprobadas.',
  },
  {
    id: 'objection-battle-es-006',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Estoy ocupado.” ¿Cuál es la respuesta segura más fuerte?',
    options: [
      'Lo entiendo. Antes de dejarlo ir, ¿estaría bien conectarlo con el Service Advisor para que le explique las opciones, o le queda mejor otro momento?',
      'Le prometo que será menos de un minuto.',
      'Tiene que quedarse en la llamada.',
      'Lo voy a transferir aunque esté ocupado.',
    ],
    correct: 0,
    explanation: 'Reconoce el tiempo del cliente, pide permiso y no uses promesas falsas de duración.',
  },
  {
    id: 'objection-battle-es-007',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Solo mándeme la información.” ¿Cuál es la mejor respuesta?',
    options: [
      'El Service Advisor tendría que revisar las opciones con usted directamente para saber qué aplica antes de enviar cualquier información.',
      'Claro, se la mando, pero primero lo transfiero sin explicar.',
      'Nunca podemos enviar nada.',
      'Lo voy a marcar aprobado y enviar papeles.',
    ],
    correct: 0,
    explanation: 'No prometas documentos o aprobación. Explica que el advisor debe revisar qué aplica.',
  },
  {
    id: 'objection-battle-es-008',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Yo no tomo decisiones. Mi esposo/a maneja eso.” ¿Cuál es la mejor respuesta?',
    options: [
      'No hay problema. ¿Está disponible ahora para que el Service Advisor pueda revisar las opciones con la persona que decide?',
      'Usted puede decidir por esa persona.',
      'Lo voy a transferir aunque no pueda decidir.',
      'Está bien, pongo la cobertura a su nombre.',
    ],
    correct: 0,
    explanation: 'La persona que decide debe estar involucrada antes de avanzar.',
  },
  {
    id: 'objection-battle-es-009',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Mi carro está bien, no necesito nada.” ¿Cuál es la mejor respuesta?',
    options: [
      'Me alegra escuchar eso. Normalmente esto se revisa mientras el vehículo todavía funciona bien, para que el advisor explique qué opciones podrían estar disponibles.',
      'Si está bien, entonces tiene que comprar cobertura ahora.',
      'Seguro se va a dañar pronto.',
      'Entonces lo transfiero sin preguntar.',
    ],
    correct: 0,
    explanation: 'Usa la buena condición del vehículo como razón para revisar opciones, sin meter miedo ni presión.',
  },
  {
    id: 'objection-battle-es-010',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “No puedo pagar nada ahora.” ¿Cuál es la respuesta más segura?',
    options: [
      'Lo entiendo. El Service Advisor puede revisar qué opciones hay disponibles, y usted decide si alguna tiene sentido para usted.',
      'No se preocupe, será gratis.',
      'Hoy le van a bajar el pago.',
      'Tiene que pagar hoy para mantenerse protegido.',
    ],
    correct: 0,
    explanation: 'No prometas cobertura gratis, pagos más bajos ni requisitos de pago.',
  },
  {
    id: 'objection-battle-es-011',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Necesito hablar primero con mi esposo/a.” ¿Cuál es la mejor respuesta?',
    options: [
      'Claro. ¿Está disponible ahora? Así el Service Advisor puede explicarles las opciones a ambos al mismo tiempo.',
      'No necesita hablar con esa persona.',
      'Solo diga que sí y luego le cuenta.',
      'Lo transfiero y después lo resuelven.',
    ],
    correct: 0,
    explanation: 'Respeta el proceso de decisión e intenta incluir a la otra persona si está disponible.',
  },
  {
    id: 'objection-battle-es-012',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Estoy en el trabajo.” ¿Cuál es la mejor respuesta?',
    options: [
      'Lo entiendo. ¿Ahora todavía estaría bien conectarlo con el Service Advisor, o sería mejor programar un callback?',
      'Su trabajo puede esperar.',
      'Esto es obligatorio, quédese en línea.',
      'Le prometo que será menos de un minuto.',
    ],
    correct: 0,
    explanation: 'Dale una opción profesional sin forzar ni prometer tiempo.',
  },
  {
    id: 'objection-battle-es-013',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “No recuerdo haber pedido esto.” ¿Cuál es la respuesta más segura?',
    options: [
      'Está bien. Solo estoy verificando la información del vehículo y revisando si hay opciones disponibles para que usted pueda evaluarlas.',
      'Usted definitivamente lo pidió, entonces tiene que continuar.',
      'Su lender lo pidió por usted.',
      'No importa si lo pidió o no.',
    ],
    correct: 0,
    explanation: 'Mantente neutral y explica el propósito. No discutas ni inventes la fuente.',
  },
  {
    id: 'objection-battle-es-014',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “¿Me puede decir el nombre de la compañía?” ¿Cuál es la mejor respuesta?',
    options: [
      'Puedo explicarle el propósito de la llamada, y el Service Advisor puede revisar los detalles del programa directamente con usted.',
      'No puedo decirle nada.',
      'Es de parte de su banco.',
      'El nombre de la compañía no importa.',
    ],
    correct: 0,
    explanation: 'Sé transparente con el propósito sin hacer afirmaciones no aprobadas.',
  },
  {
    id: 'objection-battle-es-015',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Solo quiero saber si califico.” ¿Cuál es la mejor respuesta?',
    options: [
      'Eso es justamente lo que el Service Advisor puede ayudar a revisar después de verificar el vehículo y conectarlo con él.',
      'Usted ya califica para todo.',
      'No puede calificar a menos que pague hoy.',
      'Lo voy a marcar aprobado sin revisar.',
    ],
    correct: 0,
    explanation: 'No garantices elegibilidad. Usa al Service Advisor para la revisión.',
  },
  {
    id: 'objection-battle-es-016',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “No soy el dueño, solo soy co-signer.” ¿Qué debe hacer el agente?',
    options: [
      'Aclarar quién es la persona que decide o el dueño actual antes de cualquier transferencia.',
      'Transferir al co-signer como XFER válido de todas formas.',
      'Decirle que es responsable y debe continuar.',
      'Ignorar eso y seguir leyendo el script.',
    ],
    correct: 0,
    explanation: 'El agente debe aclarar autoridad de decisión antes de transferir.',
  },
  {
    id: 'objection-battle-es-017',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Tengo la luz de check engine prendida.” ¿Cuál es la respuesta más segura?',
    options: [
      'Aclarar la condición actual del vehículo antes de avanzar, porque problemas mecánicos actuales pueden afectar elegibilidad.',
      'Transferirlo igual y ocultar ese detalle.',
      'Decir que eso no importa.',
      'Decir que el advisor cubrirá esa reparación hoy.',
    ],
    correct: 0,
    explanation: 'Problemas mecánicos actuales necesitan aclaración. No prometas cobertura para problemas existentes.',
  },
  {
    id: 'objection-battle-es-018',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Tengo más de 180,000 millas.” ¿Cuál es la mejor acción del agente?',
    options: [
      'No empujar una transferencia limpia; aclarar elegibilidad porque el millaje está sobre el límite.',
      'Transferirlo igual porque el millaje no importa.',
      'Decirle que está aprobado.',
      'Decir que el Service Advisor ignorará las millas.',
    ],
    correct: 0,
    explanation: 'Más de 175,000 millas no es elegible, así que no debe tratarse como transferencia limpia.',
  },
  {
    id: 'objection-battle-es-019',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “Tengo un vehículo eléctrico.” ¿Cuál es la mejor respuesta?',
    options: [
      'Aclarar y evitar empujarlo como elegible, porque vehículos eléctricos no pueden ser cubiertos.',
      'Transferirlo igual.',
      'Decirle que los eléctricos siempre están cubiertos.',
      'Decir que el advisor hará una excepción.',
    ],
    correct: 0,
    explanation: 'Los vehículos eléctricos no pueden ser cubiertos, así que el agente no debe empujarlo como elegible.',
  },
  {
    id: 'objection-battle-es-020',
    mode: 'objection-battle',
    topic: 'objections',
    language: 'es',
    question_type: 'mc',
    question: 'El cliente dice: “No quiero que me transfieran.” ¿Qué debe hacer el agente?',
    options: [
      'Respetar eso, no forzar la transferencia y dispositionar la llamada según la respuesta del cliente.',
      'Transferirlo en silencio.',
      'Decirle que no tiene opción.',
      'Ponerlo en hold y marcar de todas formas.',
    ],
    correct: 0,
    explanation: 'Una transferencia necesita consentimiento. Si el cliente se niega, no se debe forzar.',
  },
]