export const validInvalidQuestions = [
  {
    id: 'valid-invalid-en-001',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The agent verifies the vehicle, asks the customer if they are okay speaking with a Service Advisor, the customer says yes, the Service Advisor speaks first, and the agent stays on the 3-way call for at least 15 seconds while both lines are connected. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 0,
    explanation: 'Valid XFER. The customer gave consent, the Service Advisor spoke first, and the agent waited long enough before leaving.',
  },
  {
    id: 'valid-invalid-en-002',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer confirms the vehicle is running, but the agent transfers immediately without asking if the customer agrees to speak with a Service Advisor. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. Vehicle verification is not the same as transfer consent.',
  },
  {
    id: 'valid-invalid-en-003',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The agent dials the Service Advisor, hears the Service Advisor answer, introduces the customer, but leaves the 3-way call after only 3 seconds. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. The agent must stay long enough to confirm both lines are connected and the conversation has started.',
  },
  {
    id: 'valid-invalid-en-004',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer hangs up while the agent is dialing the Service Advisor, before the Service Advisor speaks with the customer. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. The customer never completed a real handoff with the Service Advisor.',
  },
  {
    id: 'valid-invalid-en-005',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer gives clear approval to be transferred. The Service Advisor answers first, the agent introduces the customer, and the customer speaks with the Service Advisor for 20 seconds before asking for Spanish. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 0,
    explanation: 'Valid XFER. The English handoff happened and the customer stayed connected with the Service Advisor long enough before later requesting Spanish.',
  },
  {
    id: 'valid-invalid-en-006',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer and agent speak in English, but as soon as the Service Advisor says hello, the customer immediately says they need Spanish and no English conversation happens with the Service Advisor. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. The transfer was not successful because the English Service Advisor conversation did not actually start.',
  },
  {
    id: 'valid-invalid-en-007',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The person who answers says, “This is not my car, you have the wrong number,” but the agent still transfers them to a Service Advisor. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. Wrong person or wrong vehicle should not be transferred as a clean XFER.',
  },
  {
    id: 'valid-invalid-en-008',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer says they already have coverage and they are not interested. The agent still pushes the transfer without solving the objection or getting clear agreement. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. A customer who clearly rejects and does not agree to the handoff is not a clean transfer.',
  },
  {
    id: 'valid-invalid-en-009',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer asks, “How much is it?” The agent says the Service Advisor can explain the options, asks if they are okay speaking with them, and the customer agrees. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 0,
    explanation: 'Valid XFER. The agent did not promise a price and got permission to connect the customer with the Service Advisor.',
  },
  {
    id: 'valid-invalid-en-010',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The agent tells the customer, “This will only take less than a minute,” and uses that promise to convince the customer to accept the transfer. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. Agents should not use unsupported time promises to force or manipulate the transfer.',
  },
  {
    id: 'valid-invalid-en-011',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The agent asks the customer if they want to hear the coverage options. The customer says, “Sure,” and stays on the line while the Service Advisor starts the conversation. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 0,
    explanation: 'Valid XFER. “Sure” is clear consent when the customer understands they are being connected to hear coverage options.',
  },
  {
    id: 'valid-invalid-en-012',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The agent asks, “Is the vehicle running fine?” The customer says yes. The agent treats that “yes” as permission to transfer and dials the Service Advisor. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. Saying yes to the vehicle condition does not mean the customer consented to the transfer.',
  },
  {
    id: 'valid-invalid-en-013',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer says they are busy. The agent asks if a Service Advisor can quickly explain the options now, but the customer says no and asks for a callback. The agent transfers anyway. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. The customer refused the live handoff and requested a callback.',
  },
  {
    id: 'valid-invalid-en-014',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer says they are busy. The agent handles it properly, the customer then agrees to speak with the Service Advisor now, and the handoff is completed correctly. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 0,
    explanation: 'Valid XFER. The objection was handled and the customer gave clear permission before the transfer.',
  },
  {
    id: 'valid-invalid-en-015',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The agent connects the Service Advisor, but the Service Advisor is silent and the customer receives dead air. The agent leaves the 3-way call anyway. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. Dead air is not a successful handoff.',
  },
  {
    id: 'valid-invalid-en-016',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The Service Advisor answers first, the agent introduces the customer, the customer responds, and both continue speaking while the agent waits before leaving. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 0,
    explanation: 'Valid XFER. This is the correct handoff flow.',
  },
  {
    id: 'valid-invalid-en-017',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'A child answers the phone and says their parent is not available. The agent still transfers the child to a Service Advisor. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. A child or non-decision maker should not be transferred as a valid customer handoff.',
  },
  {
    id: 'valid-invalid-en-018',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer says the decision maker is their spouse. The spouse joins the call, confirms the vehicle, agrees to hear the options, and the handoff is completed correctly. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 0,
    explanation: 'Valid XFER. The actual decision maker joined, gave consent, and completed the handoff.',
  },
  {
    id: 'valid-invalid-en-019',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer asks where the agent got their information. The agent says they work with vehicle records/dealership-related information, continues professionally, gets consent, and completes the handoff. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 0,
    explanation: 'Valid XFER. The agent handled the concern without making unsupported claims and got clear consent.',
  },
  {
    id: 'valid-invalid-en-020',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'en',
    question_type: 'binary',
    question: 'The customer asks where the agent got their information. The agent says, “Your bank sent us your file,” even though that is not approved, then transfers the customer. Valid or invalid XFER?',
    options: ['Valid XFER', 'Invalid XFER'],
    correct: 1,
    explanation: 'Invalid XFER. The agent used an unsupported claim to move the customer into the transfer.',
  },

  {
    id: 'valid-invalid-es-001',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El agente verifica el vehículo, pregunta si el cliente está de acuerdo en hablar con un Service Advisor, el cliente dice que sí, el Service Advisor habla primero, y el agente espera al menos 15 segundos con ambas líneas conectadas. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 0,
    explanation: 'Transferencia válida. Hubo consentimiento, el Service Advisor habló primero y el agente esperó antes de salir.',
  },
  {
    id: 'valid-invalid-es-002',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente confirma que el vehículo funciona, pero el agente transfiere de inmediato sin preguntarle si acepta hablar con un Service Advisor. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. Verificar el vehículo no es lo mismo que obtener consentimiento para transferir.',
  },
  {
    id: 'valid-invalid-es-003',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El agente llama al Service Advisor, escucha que contesta, presenta al cliente, pero sale de la llamada de 3 vías después de solo 3 segundos. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. El agente debe esperar lo suficiente para confirmar que ambas líneas estén conectadas y que la conversación haya comenzado.',
  },
  {
    id: 'valid-invalid-es-004',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente cuelga mientras el agente está llamando al Service Advisor, antes de que el Service Advisor hable con el cliente. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. El cliente nunca completó un handoff real con el Service Advisor.',
  },
  {
    id: 'valid-invalid-es-005',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente acepta claramente ser transferido. El Service Advisor contesta primero, el agente presenta al cliente, y el cliente habla con el Service Advisor por 20 segundos antes de pedir español. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 0,
    explanation: 'Transferencia válida. El handoff en inglés ocurrió y el cliente estuvo conectado con el Service Advisor antes de pedir español.',
  },
  {
    id: 'valid-invalid-es-006',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente y el agente hablan en inglés, pero apenas el Service Advisor saluda, el cliente inmediatamente dice que necesita español y no hay conversación en inglés con el Service Advisor. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. La conversación con el Service Advisor en inglés no llegó a comenzar.',
  },
  {
    id: 'valid-invalid-es-007',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'La persona que contesta dice: “Ese no es mi carro, tienen el número equivocado,” pero el agente aun así lo transfiere con un Service Advisor. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. Persona equivocada o vehículo equivocado no debe transferirse como XFER limpio.',
  },
  {
    id: 'valid-invalid-es-008',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente dice que ya tiene cobertura y que no está interesado. El agente sigue empujando la transferencia sin manejar bien la objeción ni obtener acuerdo claro. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. Si el cliente rechaza claramente y no acepta el handoff, no es una transferencia limpia.',
  },
  {
    id: 'valid-invalid-es-009',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente pregunta: “¿Cuánto cuesta?” El agente dice que el Service Advisor puede explicarle las opciones, pregunta si está de acuerdo en hablar con él, y el cliente acepta. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 0,
    explanation: 'Transferencia válida. El agente no prometió precio y obtuvo permiso para conectar al cliente con el Service Advisor.',
  },
  {
    id: 'valid-invalid-es-010',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El agente le dice al cliente: “Esto tomará menos de un minuto,” y usa esa promesa para convencerlo de aceptar la transferencia. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. No se deben usar promesas de tiempo no aprobadas para forzar o manipular la transferencia.',
  },
  {
    id: 'valid-invalid-es-011',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El agente pregunta si el cliente quiere escuchar las opciones de cobertura. El cliente dice “Sure” y se mantiene en línea mientras el Service Advisor inicia la conversación. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 0,
    explanation: 'Transferencia válida. “Sure” funciona como consentimiento claro cuando el cliente entiende que será conectado para escuchar opciones.',
  },
  {
    id: 'valid-invalid-es-012',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El agente pregunta: “¿El vehículo está funcionando bien?” El cliente dice que sí. El agente toma ese “sí” como permiso para transferir y llama al Service Advisor. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. Decir sí sobre la condición del vehículo no significa que el cliente aceptó la transferencia.',
  },
  {
    id: 'valid-invalid-es-013',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente dice que está ocupado. El agente pregunta si un Service Advisor puede explicarle las opciones ahora, pero el cliente dice que no y pide callback. El agente transfiere de todas formas. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. El cliente rechazó el handoff en vivo y pidió callback.',
  },
  {
    id: 'valid-invalid-es-014',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente dice que está ocupado. El agente lo maneja correctamente, el cliente luego acepta hablar con el Service Advisor ahora, y el handoff se completa bien. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 0,
    explanation: 'Transferencia válida. La objeción fue manejada y el cliente dio permiso claro antes de la transferencia.',
  },
  {
    id: 'valid-invalid-es-015',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El agente conecta al Service Advisor, pero el Service Advisor queda en silencio y el cliente recibe dead air. El agente sale de la llamada de 3 vías de todas formas. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. Dead air no es un handoff exitoso.',
  },
  {
    id: 'valid-invalid-es-016',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El Service Advisor contesta primero, el agente presenta al cliente, el cliente responde, y ambos continúan hablando mientras el agente espera antes de salir. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 0,
    explanation: 'Transferencia válida. Ese es el flujo correcto del handoff.',
  },
  {
    id: 'valid-invalid-es-017',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'Un niño contesta el teléfono y dice que su papá o mamá no está disponible. El agente aun así transfiere al niño con un Service Advisor. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. Un niño o persona que no toma decisiones no debe transferirse como cliente válido.',
  },
  {
    id: 'valid-invalid-es-018',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente dice que quien decide es su esposo/a. El esposo/a entra a la llamada, confirma el vehículo, acepta escuchar las opciones, y el handoff se completa correctamente. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 0,
    explanation: 'Transferencia válida. La persona que decide entró a la llamada, dio consentimiento y completó el handoff.',
  },
  {
    id: 'valid-invalid-es-019',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente pregunta de dónde sacaron su información. El agente dice que trabajan con registros de vehículos/información relacionada con dealerships, continúa profesionalmente, obtiene consentimiento y completa el handoff. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 0,
    explanation: 'Transferencia válida. El agente manejó la preocupación sin decir algo no aprobado y obtuvo consentimiento claro.',
  },
  {
    id: 'valid-invalid-es-020',
    mode: 'valid-invalid',
    topic: 'valid-invalid',
    language: 'es',
    question_type: 'binary',
    question: 'El cliente pregunta de dónde sacaron su información. El agente dice: “Su banco nos mandó su archivo,” aunque eso no está aprobado, y luego transfiere al cliente. ¿Transferencia válida o inválida?',
    options: ['Transferencia válida', 'Transferencia inválida'],
    correct: 1,
    explanation: 'Transferencia inválida. El agente usó una afirmación no aprobada para mover al cliente a la transferencia.',
  },
]