export const scripts = {
  en: {
    id: 'script-en',
    title: 'English Script',
    flag: '🇺🇸',
    steps: [
      {
        id: 1,
        type: 'line',
        label: 'Introduction',
        text: "Hi, [client's name] this is [your name] with the Vehicle Services Group. We're calling about the vehicle you financed on [month, year].",
        tip: 'Say the client name clearly. State month and year from the form.',
      },
      {
        id: 2,
        type: 'line',
        label: 'Purpose',
        text: "Our records indicate you haven't activated your vehicle's extended warranty yet.",
        tip: 'Say this with confidence. It creates urgency.',
      },
      {
        id: 3,
        type: 'line',
        label: 'Vehicle Check',
        text: 'I just need to verify — is your vehicle still in good running condition?',
        tip: 'Wait for the answer. This confirms eligibility.',
      },
      {
        id: 4,
        type: 'bridge',
        label: 'Positive Response',
        text: 'Perfect!',
        tip: 'Respond positively and move immediately into the transfer line.',
      },
      {
        id: 5,
        type: 'line',
        label: 'Transfer Setup',
        text: 'I would just need to get you on with a Service Advisor to explain the details of your qualifications and review what it will cover — give me one second and I will introduce you. Okay?',
        tip: 'Ask for approval clearly before transferring.',
      },
      {
        id: 6,
        type: 'action',
        label: '⚠️ Wait for Approval',
        text: 'Wait for customer approval before transferring.',
        tip: 'Never transfer without a clear okay or sure from the customer.',
      },
      {
        id: 7,
        type: 'action',
        label: '⚠️ On Transfer',
        text: 'When transferring, wait for Service Advisor to pick up the call and speak first.',
        tip: 'Do not jump in before the Service Advisor.',
      },
      {
        id: 8,
        type: 'line',
        label: 'SA Introduction',
        text: 'Hello Service Advisor, I have [client name] on the line — can you please assist?',
        tip: 'Stay on the line until the SA confirms they have the customer.',
      },
      {
        id: 9,
        type: 'action',
        label: '⏱️ 15-Second Rule',
        text: 'After the SA joins, stay on the call for at least 15 seconds before disconnecting. Make sure the SA and customer are actively talking before you leave.',
        tip: 'Never hang up the moment the SA joins.',
      },
    ],
  },

  es: {
    id: 'script-es',
    title: 'Script en Español',
    flag: '🇪🇸',
    steps: [
      {
        id: 1,
        type: 'line',
        label: 'Introducción',
        text: 'Hola, [nombre del cliente], le habla [tu nombre] de Grupo de Servicios Vehiculares. Le llamamos con respecto al vehículo que usted financió en [mes, año].',
        tip: 'Di el nombre del cliente claramente. Menciona mes y año del formulario.',
      },
      {
        id: 2,
        type: 'line',
        label: 'Propósito',
        text: 'Nuestros registros indican que aún no ha activado la garantía extendida de su vehículo.',
        tip: 'Di esto con confianza. Crea urgencia.',
      },
      {
        id: 3,
        type: 'line',
        label: 'Verificación del vehículo',
        text: 'Solo necesito verificar: ¿Su vehículo se encuentra actualmente en buenas condiciones de funcionamiento?',
        tip: 'Espera la respuesta. Esto confirma elegibilidad.',
      },
      {
        id: 4,
        type: 'bridge',
        label: 'Respuesta positiva',
        text: '¡Perfecto!',
        tip: 'Responde positivamente y pasa inmediatamente a la transferencia.',
      },
      {
        id: 5,
        type: 'line',
        label: 'Preparación de transferencia',
        text: 'Lo voy a comunicar con un Asesor de Servicio para que le explique los detalles de su calificación y revise qué es lo que cubriría. Deme un segundo y se lo presento. ¿Okay?',
        tip: 'Pide aprobación con claridad antes de transferir.',
      },
      {
        id: 6,
        type: 'action',
        label: '⚠️ Espera aprobación',
        text: 'Espera primero por aprobación del cliente para transferir.',
        tip: 'Nunca transfieras sin un sí o okay claro.',
      },
      {
        id: 7,
        type: 'action',
        label: '⚠️ Al transferir',
        text: 'Al transferir, espera a que el Asesor de Servicio conteste y hable primero.',
        tip: 'No te adelantes al SA.',
      },
      {
        id: 8,
        type: 'line',
        label: 'Introducción al Asesor',
        text: 'Hola, Asesor de Servicio, tengo a [nombre del cliente] en la línea. ¿Podría asistir, por favor?',
        tip: 'Quédate en la línea hasta que el SA confirme que tiene al cliente.',
      },
      {
        id: 9,
        type: 'action',
        label: '⏱️ Regla de 15 segundos',
        text: 'Después de que el Asesor se une, permanece en la llamada al menos 15 segundos antes de desconectarte. Asegúrate de que el SA y el cliente estén hablando activamente antes de salir.',
        tip: 'Nunca cuelgues apenas entra el SA.',
      },
    ],
  },
}

export const objections = [
  {
    id: 'not-interested',
    emoji: '🚫',
    title: 'Not Interested',
    titleEs: 'No me interesa',
    goal: 'Keep them on the line and create curiosity',
    rebuttalEn:
      'I completely understand. A lot of people felt the same way at first until they saw how much a single repair could cost without coverage. That is exactly why we do not charge for the quote with the Service Advisor. Fair enough?',
    rebuttalEs:
      'Entiendo perfectamente. Mucha gente pensaba lo mismo al principio hasta que vio cuánto puede costar una sola reparación sin cobertura. Por eso no cobramos nada por la consulta con el Asesor de Servicio. ¿Le parece bien?',
  },
  {
    id: 'no-service',
    emoji: '❓',
    title: "I don't have any service with you",
    titleEs: 'No tengo ningún servicio con ustedes',
    goal: 'Clarify purpose and shift into value mode',
    rebuttalEn:
      'Exactly, and that is why we are reaching out today. This is your opportunity to activate a protection plan for your vehicle.',
    rebuttalEs:
      'Exactamente, y por eso le estamos llamando hoy. Esta es su oportunidad de activar un plan de protección para su vehículo.',
  },
  {
    id: 'where-info',
    emoji: '📋',
    title: 'Where did you get my information?',
    titleEs: '¿Cómo obtuvieron mi información?',
    goal: 'Normalize the contact and build trust',
    rebuttalEn:
      'We partner with dealerships and vehicle registries nationwide, and your vehicle information is part of our outreach for protection eligibility.',
    rebuttalEs:
      'Trabajamos con concesionarios y registros vehiculares a nivel nacional, y la información de su vehículo forma parte de nuestro alcance para elegibilidad de protección.',
  },
  {
    id: 'what-vehicle',
    emoji: '🚗',
    title: 'What kind of vehicle?',
    titleEs: '¿Qué tipo de vehículo?',
    goal: 'Show limitations and move toward the Service Advisor',
    rebuttalEn:
      'I only see the finance information here, not the exact make or model. That is why I need to get you over to the Service Advisor.',
    rebuttalEs:
      'Solo tengo la información financiera aquí, no la marca o modelo exacto. Por eso necesito comunicarle con el Asesor de Servicio.',
  },
  {
    id: 'where-located',
    emoji: '🌎',
    title: 'Where are you located?',
    titleEs: '¿Dónde están ubicados?',
    goal: 'Build credibility',
    rebuttalEn:
      'Our headquarters are based in Dallas, Texas, but our protection plans are accepted at authorized repair facilities across the U.S.',
    rebuttalEs:
      'Nuestra sede está en Dallas, Texas, pero nuestros planes de protección son aceptados en talleres autorizados en todo EE.UU.',
  },
  {
    id: 'who-is-this',
    emoji: '📞',
    title: 'Who is this?',
    titleEs: '¿Quién habla?',
    goal: 'Clarify and validate',
    rebuttalEn:
      'This is [your name] from the Vehicle Services Group.',
    rebuttalEs:
      'Le habla [tu nombre] del Grupo de Servicios Vehiculares.',
  },
  {
    id: 'how-much',
    emoji: '💲',
    title: 'How much does it cost?',
    titleEs: '¿Cuánto cuesta?',
    goal: 'Tease the value and move toward transfer',
    rebuttalEn:
      'That is the great part. Cost depends on mileage and driving habits, and the Service Advisor can break that down for you.',
    rebuttalEs:
      'Esa es la mejor parte. El costo depende del millaje y hábitos de manejo, y el Asesor de Servicio puede explicárselo.',
  },
  {
    id: 'already-insurance',
    emoji: '🛡️',
    title: 'I already have insurance',
    titleEs: 'Ya tengo seguro',
    goal: 'Differentiate coverage clearly',
    rebuttalEn:
      'Totally understand. Insurance covers accidents. What we offer is mechanical breakdown coverage.',
    rebuttalEs:
      'Totalmente entendido. El seguro cubre accidentes. Lo que ofrecemos es cobertura por fallas mecánicas.',
  },
  {
    id: 'busy',
    emoji: '🕒',
    title: "I'm busy",
    titleEs: 'Estoy ocupado/a',
    goal: 'Keep control and offer a callback',
    rebuttalEn:
      'Totally respect that. If this is not a good time, I can schedule a callback that works better for you.',
    rebuttalEs:
      'Lo respeto totalmente. Si este no es un buen momento, puedo agendar una llamada de regreso.',
  },
  {
    id: 'already-activated',
    emoji: '✅',
    title: 'I already activated it',
    titleEs: 'Ya la activé',
    goal: 'Differentiate factory warranty and extended coverage',
    rebuttalEn:
      'If that was activated when you first purchased the vehicle, it is likely just the Factory Warranty. We are looking at Extended Warranty coverage, which is wider.',
    rebuttalEs:
      'Si eso se activó cuando compró el vehículo, probablemente sea solo la Garantía de Fábrica. Nosotros hablamos de Garantía Extendida, que es más amplia.',
  },
  {
    id: 'another-company',
    emoji: '🏢',
    title: 'I have it with another company',
    titleEs: 'La tengo con otra compañía',
    goal: 'Highlight comparison opportunity',
    rebuttalEn:
      'That is great because it gives you a baseline. Many clients switch after a quick side by side comparison.',
    rebuttalEs:
      'Eso es excelente porque le da un punto de comparación. Muchos clientes cambian después de una comparación rápida.',
  },
  {
    id: 'purpose-of-call',
    emoji: '📣',
    title: 'Purpose of the call?',
    titleEs: '¿Cuál es el propósito de la llamada?',
    goal: 'Clarify purpose and move toward transfer',
    rebuttalEn:
      'This call is simply an opportunity to extend protection on your vehicle before any issues come up.',
    rebuttalEs:
      'Esta llamada es simplemente una oportunidad para extender la protección de su vehículo antes de que surja algún problema.',
  },
]

export const productKnowledge = {
  comparison: {
    title: 'Know the Difference',
    items: [
      {
        name: 'Factory Warranty',
        color: '#b45309',
        points: [
          'Comes with new vehicles',
          'Lasts about 3 years or 36,000 miles',
          'Covers manufacturer defects',
          'Expires and cannot be renewed as factory coverage',
        ],
      },
      {
        name: 'Extended Coverage',
        color: '#f97316',
        points: [
          'Not mandatory',
          'Covers mechanical repairs after factory coverage ends',
          'Optional product',
          'That is what we offer',
        ],
      },
      {
        name: 'Insurance',
        color: '#92400e',
        points: [
          'Mandatory in the U.S. to drive legally',
          'Covers accidents, theft, damage, liability',
          'Does not cover mechanical breakdowns',
          'Completely different product',
        ],
      },
    ],
  },

  canCover: {
    title: 'What We Cover',
    items: [
      'Engine and transmission',
      'Vehicles manufactured 2011 or later',
      'Vehicles with up to 175,000 miles',
      'Vehicles that still run',
      'Coverage up to 100,000 or more additional miles',
      'Repairs at any authorized repair shop nationwide',
      'Unmodified parts on vehicles with modifications',
    ],
  },

  cannotCover: {
    title: 'What We Cannot Cover',
    items: [
      'Electric vehicles',
      'Vehicles before 2011',
      'Vehicles with over 175,000 miles',
      'Bodywork or cosmetic repairs',
      'Collision or accident damage',
      'Light bulbs and normal wear items',
      'Modified parts themselves',
      'Motorcycles, trailers, exotic exceptions',
    ],
  },

  duration: {
    title: 'Duration and Service Process',
    points: [
      'Kicks in after factory coverage ends',
      'Can cover up to 100,000 or more additional miles',
      'Service can be done at authorized repair facilities across the U.S.',
    ],
  },
}

export const callFlow = {
  steps: [
    {
      id: 1,
      title: 'Introduction and Financing Info',
      icon: '👋',
      description: 'Greet the client by name, identify yourself and the company, and mention the financing month and year.',
      keyPoints: ['Use the client name', 'Use month and year from form', 'Sound confident'],
    },
    {
      id: 2,
      title: 'Vehicle Condition Verification',
      icon: '🚗',
      description: 'Ask whether the vehicle is still in good running condition. This confirms eligibility.',
      keyPoints: ['Wait for the answer', 'Vehicle must be running', 'Do not skip this step'],
    },
    {
      id: 3,
      title: 'Transfer Setup',
      icon: '📋',
      description: 'Explain that you need to connect the customer with a Service Advisor and get approval first.',
      keyPoints: ['Get clear approval', 'Never transfer without consent', 'Be direct and smooth'],
    },
    {
      id: 4,
      title: 'Professional Transfer',
      icon: '🔄',
      description: 'Wait for the Service Advisor to pick up first, then introduce the client by name and stay on the line.',
      keyPoints: ['SA speaks first', 'Introduce client properly', 'Confirm handoff before leaving'],
    },
  ],

  transferProtocol: [
    'Confirm vehicle qualification first',
    'Get customer approval to transfer',
    'Initiate the transfer and stay on the line',
    'Wait for the Service Advisor to pick up and speak first',
    'Introduce the client by name',
    'Stay at least 15 seconds and confirm both are talking',
  ],

  waitingQuestions: [
    'Has your vehicle received maintenance recently?',
    'Have you noticed any unusual noises from the engine or transmission?',
    'Have you had any breakdowns or repairs recently?',
    'Does the vehicle start without problems?',
    'Have you seen any warning lights on the dashboard?',
    'Do the brakes respond properly?',
    'Are you satisfied with your vehicle performance so far?',
    'Has the vehicle had any modifications or upgrades?',
  ],
}

export const dosAndDonts = {
  donts: [
    {
      rule: "Don't say we work for car brands",
      detail: 'We are Vehicle Services Group, independent.',
    },
    {
      rule: "Don't say we are extending factory warranty",
      detail: 'We offer extended coverage, which is a separate product.',
    },
    {
      rule: 'Never say FREE',
      detail: 'This is misleading and non-compliant.',
    },
    {
      rule: "Don't say the bank gave us the information",
      detail: 'Say we partner with dealerships and vehicle registries.',
    },
  ],

  formFields: {
    use: [
      'Customer first and last name',
      'Origination date or date of loan',
      'Loan balance or total amount of loan',
    ],
    ignore: [
      'Address',
      'Maintenance dates',
      'Finance company',
      'Terms of loan',
      'Plan cost',
    ],
  },

  deliveryStandards: [
    'State financing info with confidence',
    'Confirm the vehicle runs before continuing',
    'Use proper SA introduction',
    'Do not shorten the script',
    'Do not improvise the wording',
  ],

  practiceStructure: [
    {
      title: 'Line by Line Repetition',
      desc: 'Repeat the script exactly as written until delivery becomes natural.',
    },
    {
      title: 'Tone and Pronunciation',
      desc: 'Focus on clear pronunciation, controlled energy, and confident inflection.',
    },
    {
      title: 'Authority',
      desc: 'Speak with control, clarity, and purpose.',
    },
    {
      title: 'Speed Control',
      desc: 'Do not rush. Do not drag. Keep a balanced pace.',
    },
  ],
}

export const dialer = {
  dispositions: [
    { code: 'A', label: 'Answering Machine', description: 'Voicemail or automated system' },
    { code: 'BLANK', label: 'No Info on File', description: 'No usable customer info' },
    { code: 'CALLBK', label: 'Call Back', description: 'Customer requested callback' },
    { code: 'DAIR', label: 'Dead Air', description: 'Call connected but nobody responded' },
    { code: 'DC', label: 'Disconnected Number', description: 'Number no longer in service' },
    { code: 'DNC', label: 'Do Not Call', description: 'Customer asked to be removed' },
    { code: 'LANG', label: 'Language Barrier', description: 'Could not communicate due to language' },
    { code: 'NI', label: 'Not Interested', description: 'Customer declined' },
    { code: 'SPANIS', label: 'Spanish Speaker', description: 'Spanish speaker routing' },
    { code: 'SPXFER', label: 'Spanish Xfer', description: 'Transferred to Spanish Service Advisor' },
    { code: 'WRGNUM', label: 'Wrong Number', description: 'Number does not match file' },
    { code: 'WRGVEH', label: 'Wrong Vehicle Info', description: 'Vehicle info on file is incorrect' },
    { code: 'XFER', label: 'Call Transferred', description: 'Successful transfer to Service Advisor' },
  ],

  pauseCodes: [
    { code: 'Break - Break', label: 'BREAK', time: '10 minutes max', desc: 'Scheduled break only' },
    { code: 'CB - Callbacks', label: 'CALLBACKS', time: 'As needed', desc: 'For callbacks' },
    { code: 'Lunch - Lunch', label: 'LUNCH', time: '1 hour', desc: 'Lunch only' },
    { code: 'Manage', label: 'MANAGE', time: 'As needed', desc: 'When supervisor asks you to call them' },
    { code: 'RR - Restroom', label: 'RESTROOM', time: '5 minutes max', desc: 'Restroom only' },
    { code: 'Tech - Tech or System Issues', label: 'TECH ISSUES', time: 'As needed', desc: 'System problems' },
  ],
}

export const quizQuestions = [
  {
    id: 1,
    topic: "script",
    language: "en",
    question: "Which company name should the opener use in the English introduction?",
    options: [
      "Vehicle Services Group",
      "Vehicle Service Center",
      "Auto Warranty Department",
      "Coverage Review Team",
    ],
    correct: 0,
    explanation: "The English opening identifies the caller as being with the Vehicle Services Group.",
  },
  {
    id: 2,
    topic: "script",
    language: "en",
    question: "What financing detail belongs in the opening line?",
    options: [
      "The dealership street address",
      "The month and year financed",
      "The APR percentage shown",
      "The customer ZIP code",
    ],
    correct: 1,
    explanation: "The opener should mention the vehicle financed on the month and year shown on the form.",
  },
  {
    id: 3,
    topic: "script",
    language: "en",
    question: "What must be verified before moving toward a transfer?",
    options: [
      "That the customer knows the VIN",
      "That the address is fully updated",
      "That the vehicle is running well",
      "That the customer has repair receipts",
    ],
    correct: 2,
    explanation: "The opener must confirm the vehicle is still in good running condition before transferring.",
  },
  {
    id: 4,
    topic: "script",
    language: "en",
    question: "Which line best matches the approved purpose statement?",
    options: [
      "Your bank asked us to renew the factory warranty today",
      "The dealership wants us to sell a new policy now",
      "We are calling to confirm your insurance coverage",
      "Our records show the extended warranty has not been activated yet",
    ],
    correct: 3,
    explanation: "The purpose line is about the vehicle’s extended warranty not being activated yet.",
  },
  {
    id: 5,
    topic: "script",
    language: "en",
    question: "What should the opener do before starting the transfer?",
    options: [
      "Ask for the full VIN number",
      "Get clear approval from the customer",
      "Quote the exact monthly price",
      "Read the dealership address",
    ],
    correct: 1,
    explanation: "The customer must clearly approve the transfer before the opener connects the call.",
  },
  {
    id: 6,
    topic: "script",
    language: "en",
    question: "Which handoff line is the most professional?",
    options: [
      "I have someone here. Please take this call now.",
      "This person wants prices. Go ahead and explain.",
      "Hello Service Advisor, I have the customer on the line. Can you please assist?",
      "The customer is ready, so I am leaving the call.",
    ],
    correct: 2,
    explanation: "The handoff must introduce the customer to the Service Advisor in a clean and professional way.",
  },
  {
    id: 7,
    topic: "script",
    language: "es",
    question: "For the Spanish script, which company name should be used?",
    options: [
      "Centro Nacional de Bancos",
      "Departamento de Seguros del Dealer",
      "Garantía Directa del Fabricante",
      "Grupo de Servicios Vehiculares",
    ],
    correct: 3,
    explanation: "The Spanish script identifies the caller as Grupo de Servicios Vehiculares.",
  },
  {
    id: 8,
    topic: "script",
    language: "es",
    question: "What does the Spanish opener verify before transferring?",
    options: [
      "That the vehicle is in good running condition",
      "That the customer has full insurance",
      "That the loan balance is paid off",
      "That the address matches the file",
    ],
    correct: 0,
    explanation: "The Spanish script still requires vehicle condition verification before the transfer.",
  },
  {
    id: 9,
    topic: "script",
    language: "es",
    question: "Which Spanish transfer setup is the approved meaning?",
    options: [
      "Send the customer directly to the dealership for pricing",
      "Move the call to billing before checking eligibility",
      "Connect the customer with an Asesor de Servicio to review qualification",
      "Ask the customer to call back after checking the vehicle",
    ],
    correct: 2,
    explanation: "The Spanish transfer line connects the customer with an Asesor de Servicio for qualification details.",
  },
  {
    id: 10,
    topic: "script",
    language: "es",
    question: "In the Spanish script, when should the opener transfer?",
    options: [
      "As soon as the customer answers",
      "After the customer gives approval",
      "Before confirming the vehicle runs",
      "Only after quoting the plan cost",
    ],
    correct: 1,
    explanation: "Approval is required before transferring in both English and Spanish.",
  },
  {
    id: 11,
    topic: "script",
    language: "es",
    question: "Which Spanish handoff is closest to the approved line?",
    options: [
      "Hola, ventas, este cliente quiere saber el precio final.",
      "Buenas, le dejo a esta persona porque está interesada.",
      "Asesor, tome esta llamada mientras yo cuelgo.",
      "Hola, Asesor de Servicio, tengo al cliente en la línea. ¿Podría asistir?",
    ],
    correct: 3,
    explanation: "The Spanish handoff should introduce the customer clearly to the Asesor de Servicio.",
  },
  {
    id: 12,
    topic: "script",
    language: "es",
    question: "What should the opener avoid when delivering either script?",
    options: [
      "Shortening or improvising the wording",
      "Speaking with controlled pacing",
      "Using the customer name clearly",
      "Sounding confident with the finance info",
    ],
    correct: 0,
    explanation: "Script delivery standards require no shortening and no improvising.",
  },
  {
    id: 13,
    topic: "objections",
    language: "en",
    question: "A customer says, “I’m not interested.” What is the strongest first move?",
    options: [
      "Ask why and create curiosity",
      "End the call immediately",
      "Argue that they need coverage",
      "Skip directly to the transfer",
    ],
    correct: 0,
    explanation: "The opener should ask a question, understand the reason, and create curiosity.",
  },
  {
    id: 14,
    topic: "objections",
    language: "en",
    question: "A customer asks, “Where did you get my information?” What should you say?",
    options: [
      "Your bank sent us your loan profile today",
      "We partner with dealerships and vehicle registries nationwide",
      "We bought the file from another company",
      "The system does not show that information",
    ],
    correct: 1,
    explanation: "The approved answer references dealerships and vehicle registries, not the bank.",
  },
  {
    id: 15,
    topic: "objections",
    language: "en",
    question: "A customer asks, “What kind of vehicle?” What is the best response?",
    options: [
      "I can see the exact make and model but cannot say it",
      "You should already know which vehicle we mean",
      "I only see finance info, and the Service Advisor can review the full details",
      "That question does not matter for this call",
    ],
    correct: 2,
    explanation: "Be transparent about seeing finance information and bridge to the Service Advisor.",
  },
  {
    id: 16,
    topic: "objections",
    language: "en",
    question: "A customer asks, “How much does it cost?” What should the opener avoid?",
    options: [
      "Mentioning mileage can affect cost",
      "Moving toward the Service Advisor",
      "Explaining that pricing varies",
      "Giving an exact price",
    ],
    correct: 3,
    explanation: "The opener should not quote exact pricing; the Service Advisor reviews cost.",
  },
  {
    id: 17,
    topic: "objections",
    language: "en",
    question: "A customer says, “I already have insurance.” What distinction matters most?",
    options: [
      "Insurance and extended coverage are the same service",
      "Insurance covers accidents; this covers mechanical breakdowns",
      "Insurance replaces the need for any repair coverage",
      "Extended coverage is required by law like insurance",
    ],
    correct: 1,
    explanation: "Insurance and extended coverage are different products.",
  },
  {
    id: 18,
    topic: "objections",
    language: "en",
    question: "A customer says, “I’m busy.” What is the best control move?",
    options: [
      "Push faster through the full script",
      "Tell them it will only take seconds",
      "Offer a callback time that works better",
      "Continue talking until they answer",
    ],
    correct: 2,
    explanation: "Respect the customer’s time and offer a callback option.",
  },
  {
    id: 19,
    topic: "objections",
    language: "es",
    question: "On a Spanish call, the customer says they are not interested. What should the opener do first?",
    options: [
      "Transfer without further explanation",
      "Mark SPXFER immediately",
      "Tell them they are making a mistake",
      "Ask a quick question to understand why",
    ],
    correct: 3,
    explanation: "The same objection-handling logic applies: ask why, then work with the answer.",
  },
  {
    id: 20,
    topic: "objections",
    language: "es",
    question: "On a Spanish call, the customer asks where the company is located. What answer is approved?",
    options: [
      "Headquarters are in Dallas, Texas",
      "The office is inside the dealership",
      "The bank office manages the policy",
      "The location changes by customer state",
    ],
    correct: 0,
    explanation: "The approved location answer is Dallas, Texas, with nationwide accepted plans.",
  },
  {
    id: 21,
    topic: "objections",
    language: "es",
    question: "On a Spanish call, the customer asks, “Who is this?” What should come first?",
    options: [
      "Say the bank gave the information",
      "Say it is the dealership warranty desk",
      "Identify as Grupo de Servicios Vehiculares",
      "Skip the company name completely",
    ],
    correct: 2,
    explanation: "The first identification should match the approved Spanish company wording.",
  },
  {
    id: 22,
    topic: "objections",
    language: "es",
    question: "On a Spanish call, the customer says they already have coverage. What is the best angle?",
    options: [
      "Tell them their current coverage is invalid",
      "Review possible updated or additional benefits",
      "Tell them to cancel the current plan",
      "End the call because they cannot qualify",
    ],
    correct: 1,
    explanation: "The call should be positioned as a review of options or additional benefits, not a replacement demand.",
  },
  {
    id: 23,
    topic: "objections",
    language: "es",
    question: "On a Spanish call, the customer says the vehicle was sold or totaled. What should the opener do?",
    options: [
      "Mark it as a successful transfer",
      "Insist the old vehicle still qualifies",
      "Ask for payment information first",
      "Ask if they currently drive another vehicle",
    ],
    correct: 3,
    explanation: "Redirect toward the current vehicle and confirm whether it is running in good condition.",
  },
  {
    id: 24,
    topic: "objections",
    language: "es",
    question: "On a Spanish call, the customer says the vehicle info is wrong. What is the best approach?",
    options: [
      "Treat it as verification and check the current vehicle",
      "Tell the customer the file is always correct",
      "Skip the vehicle check and transfer anyway",
      "Mark the call as Do Not Call",
    ],
    correct: 0,
    explanation: "Wrong or outdated info should be handled as a verification opportunity.",
  },
  {
    id: 25,
    topic: "product",
    language: "en",
    question: "What does extended coverage mainly protect against?",
    options: [
      "Mechanical breakdown repairs",
      "Accident liability claims",
      "Bodywork after collisions",
      "Routine oil changes only",
    ],
    correct: 0,
    explanation: "Extended coverage is focused on mechanical breakdown repairs, not accident insurance.",
  },
  {
    id: 26,
    topic: "product",
    language: "en",
    question: "Which vehicle is most likely to qualify?",
    options: [
      "2008 coupe with 70,000 miles",
      "2018 sedan with 95,000 miles",
      "2021 electric vehicle with 30,000 miles",
      "2019 motorcycle with 15,000 miles",
    ],
    correct: 1,
    explanation: "A qualifying vehicle should be 2011 or newer, non-electric, under 175,000 miles, and not an excluded type.",
  },
  {
    id: 27,
    topic: "product",
    language: "en",
    question: "What mileage limit should agents remember?",
    options: [
      "125,000 miles",
      "150,000 miles",
      "175,000 miles",
      "200,000 miles",
    ],
    correct: 2,
    explanation: "Vehicles with more than 175,000 miles cannot be covered.",
  },
  {
    id: 28,
    topic: "product",
    language: "en",
    question: "Which item is excluded from coverage?",
    options: [
      "Engine mechanical repair",
      "Transmission mechanical repair",
      "Covered electrical failure",
      "Bodywork or cosmetic repair",
    ],
    correct: 3,
    explanation: "Bodywork and cosmetic repairs are not covered.",
  },
  {
    id: 29,
    topic: "product",
    language: "en",
    question: "How is factory warranty different from extended coverage?",
    options: [
      "Factory warranty is optional after every repair",
      "Factory warranty comes with new vehicles for a limited term",
      "Factory warranty covers accidents nationwide",
      "Factory warranty starts after extended coverage ends",
    ],
    correct: 1,
    explanation: "Factory warranty usually comes with a new vehicle and lasts for a limited time or mileage.",
  },
  {
    id: 30,
    topic: "product",
    language: "en",
    question: "Where can approved repairs generally be handled?",
    options: [
      "Only at the original dealership",
      "Only at repair shops in Texas",
      "At authorized repair facilities nationwide",
      "Only through the selling bank",
    ],
    correct: 2,
    explanation: "Approved repairs can be handled at authorized repair facilities across the U.S.",
  },
  {
    id: 31,
    topic: "product",
    language: "es",
    question: "For Spanish training, which vehicle should be treated as not eligible?",
    options: [
      "A 2016 sedan under 100,000 miles",
      "A 2018 SUV in running condition",
      "A 2015 truck with no warning lights",
      "A 2020 electric vehicle",
    ],
    correct: 3,
    explanation: "Electric vehicles are excluded from coverage.",
  },
  {
    id: 32,
    topic: "product",
    language: "es",
    question: "For Spanish training, what is the oldest model year that can still qualify?",
    options: [
      "2011",
      "2009",
      "2008",
      "2010",
    ],
    correct: 0,
    explanation: "Vehicles manufactured before 2011 cannot be covered.",
  },
  {
    id: 33,
    topic: "product",
    language: "es",
    question: "For Spanish training, what should be confirmed before discussing options?",
    options: [
      "The customer has the title available",
      "The loan is already paid off",
      "The vehicle is currently running",
      "The customer knows the exact mileage",
    ],
    correct: 2,
    explanation: "The vehicle running condition is essential for eligibility.",
  },
  {
    id: 34,
    topic: "product",
    language: "es",
    question: "For Spanish training, what is true about insurance?",
    options: [
      "It replaces extended coverage entirely",
      "It covers accidents, not mechanical breakdowns",
      "It is the same as factory warranty",
      "It pays for every repair type",
    ],
    correct: 1,
    explanation: "Insurance and extended coverage must be explained as separate products.",
  },
  {
    id: 35,
    topic: "product",
    language: "es",
    question: "For Spanish training, how should modified parts be treated?",
    options: [
      "All modified parts are always covered",
      "Any modification disqualifies the whole vehicle",
      "Only dealership modifications are excluded",
      "Modified parts are not covered, but other parts may qualify",
    ],
    correct: 3,
    explanation: "Modified parts themselves are excluded, but the vehicle may still have eligible unmodified parts.",
  },
  {
    id: 36,
    topic: "product",
    language: "es",
    question: "For Spanish training, what does “authorized repair facility” mean?",
    options: [
      "A qualified repair shop accepted by the plan",
      "Only the dealership where the car was sold",
      "Any mechanic the customer personally chooses",
      "Only a repair shop located in Dallas",
    ],
    correct: 0,
    explanation: "The plan is designed around authorized repair facilities, not only one dealership.",
  },
  {
    id: 37,
    topic: "callflow",
    language: "en",
    question: "What is the first step in a clean transfer flow?",
    options: [
      "Confirm vehicle qualification",
      "Introduce the Service Advisor",
      "Disconnect after dialing",
      "Choose the final disposition",
    ],
    correct: 0,
    explanation: "Qualification comes first, especially vehicle condition.",
  },
  {
    id: 38,
    topic: "callflow",
    language: "en",
    question: "What must happen before the opener dials the transfer?",
    options: [
      "The customer provides the VIN",
      "The customer gives clear approval",
      "The customer accepts a quoted price",
      "The SA confirms availability by chat",
    ],
    correct: 1,
    explanation: "A clean transfer requires customer approval before dialing.",
  },
  {
    id: 39,
    topic: "callflow",
    language: "en",
    question: "Who should speak first when the Service Advisor joins?",
    options: [
      "The opener immediately",
      "The customer only",
      "The Service Advisor",
      "No one until the timer ends",
    ],
    correct: 2,
    explanation: "The Service Advisor should pick up and speak first before the opener introduces the customer.",
  },
  {
    id: 40,
    topic: "callflow",
    language: "en",
    question: "How long should the opener stay after the SA joins?",
    options: [
      "At least 3 seconds",
      "Exactly 5 seconds",
      "Until the customer asks to leave",
      "At least 15 seconds",
    ],
    correct: 3,
    explanation: "The opener should stay at least 15 seconds and confirm both parties are talking.",
  },
  {
    id: 41,
    topic: "callflow",
    language: "en",
    question: "What should the opener do if the SA is silent for about 5 seconds?",
    options: [
      "Disconnect and tag the call as transferred",
      "Say “Hello Service Advisor” to get attention",
      "Tell the customer to call back later",
      "Mute the line until someone speaks",
    ],
    correct: 1,
    explanation: "The opener should call the advisor’s attention to avoid a hang-up and protect the transfer.",
  },
  {
    id: 42,
    topic: "callflow",
    language: "en",
    question: "What should happen if the customer asks the SA for a callback?",
    options: [
      "Tag it as XFER because the SA joined",
      "Tag it as SPANIS automatically",
      "Tag it as Call Back, not XFER",
      "Tag it as Dead Air",
    ],
    correct: 2,
    explanation: "If the customer asks the SA for a callback, it should be Call Back rather than XFER.",
  },
  {
    id: 43,
    topic: "callflow",
    language: "es",
    question: "For a Spanish transfer, what should be selected during the transfer process?",
    options: [
      "Blind Transfer before speaking to the SA",
      "Hangup Both Lines as soon as it rings",
      "Do Not Call before dialing the advisor",
      "Spanish option before completing the transfer",
    ],
    correct: 3,
    explanation: "Spanish transfers require selecting the Spanish option in the dialer flow.",
  },
  {
    id: 44,
    topic: "callflow",
    language: "es",
    question: "For a Spanish call, what should the opener do while waiting for the advisor?",
    options: [
      "Keep the customer engaged with light vehicle questions",
      "Stay silent until the advisor appears",
      "Ask for banking details",
      "Promise the price will be low",
    ],
    correct: 0,
    explanation: "Waiting questions prevent dead air and keep the customer connected.",
  },
  {
    id: 45,
    topic: "callflow",
    language: "es",
    question: "For Spanish transfer protocol, what confirms the handoff is safe?",
    options: [
      "The opener hears one ring only",
      "The opener has already clicked transfer",
      "The advisor and customer are actively talking",
      "The customer said “hello” once",
    ],
    correct: 2,
    explanation: "A safe handoff requires both parties to be actively talking before leaving.",
  },
  {
    id: 46,
    topic: "callflow",
    language: "es",
    question: "For Spanish calls, when is it wrong to tag XFER?",
    options: [
      "When the advisor and customer are connected",
      "When the customer hangs up before a real handoff",
      "When the opener waited and introduced properly",
      "When the customer clearly agreed to transfer",
    ],
    correct: 1,
    explanation: "A hang-up before a real handoff should not be treated as a valid transfer.",
  },
  {
    id: 47,
    topic: "callflow",
    language: "es",
    question: "For Spanish calls, what should the opener note if the SA took too long to respond?",
    options: [
      "That the customer refused all coverage",
      "That the opener skipped the introduction",
      "That the system created a wrong number",
      "That the SA delayed response after connection",
    ],
    correct: 3,
    explanation: "If the SA delay caused risk, notes should explain the delayed advisor response.",
  },
  {
    id: 48,
    topic: "callflow",
    language: "es",
    question: "For Spanish calls, what is the opener’s role during transfer?",
    options: [
      "Connect, introduce, wait, and verify the conversation",
      "Quote final pricing and close the sale",
      "Leave immediately after pressing transfer",
      "Argue objections while the SA is speaking",
    ],
    correct: 0,
    explanation: "The opener must complete a controlled handoff, not abandon the call.",
  },
  {
    id: 49,
    topic: "dosdonts",
    language: "en",
    question: "Which phrase should agents avoid?",
    options: [
      "This is free",
      "This is an opportunity to review options",
      "The Service Advisor can explain details",
      "Let me verify the vehicle condition",
    ],
    correct: 0,
    explanation: "Agents should not use “free” because it can be misleading.",
  },
  {
    id: 50,
    topic: "dosdonts",
    language: "en",
    question: "Which statement is not allowed?",
    options: [
      "We partner with vehicle registries",
      "The bank gave us your information",
      "The Service Advisor reviews details",
      "I only see finance information",
    ],
    correct: 1,
    explanation: "Agents should not say the bank gave the information.",
  },
  {
    id: 51,
    topic: "dosdonts",
    language: "en",
    question: "Which delivery behavior is required?",
    options: [
      "Shorten the script to save time",
      "Change wording based on preference",
      "Read the script without improvising",
      "Skip the vehicle condition check",
    ],
    correct: 2,
    explanation: "Script compliance means no improvising and no skipping required parts.",
  },
  {
    id: 52,
    topic: "dosdonts",
    language: "en",
    question: "Which disposition fits a completed English transfer?",
    options: [
      "SPXFER",
      "SPANIS",
      "CALLBK",
      "XFER",
    ],
    correct: 3,
    explanation: "XFER is for a valid English call transferred to a Service Advisor.",
  },
  {
    id: 53,
    topic: "dosdonts",
    language: "en",
    question: "Which pause code should be used for a supervisor-requested call?",
    options: [
      "RR",
      "Manage",
      "Lunch",
      "Break",
    ],
    correct: 1,
    explanation: "Manage is used when a supervisor asks the agent to call or talk to them.",
  },
  {
    id: 54,
    topic: "dosdonts",
    language: "en",
    question: "Which pause code fits a restroom pause?",
    options: [
      "CB",
      "Tech",
      "RR",
      "Manage",
    ],
    correct: 2,
    explanation: "RR is the restroom pause code.",
  },
  {
    id: 55,
    topic: "dosdonts",
    language: "es",
    question: "For a blind Spanish transfer, which disposition should be used?",
    options: [
      "SPXFER",
      "XFER",
      "LANG",
      "SPANIS",
    ],
    correct: 3,
    explanation: "Blind Spanish transfers must use SPANIS, not SPXFER.",
  },
  {
    id: 56,
    topic: "dosdonts",
    language: "es",
    question: "When should SPXFER be used?",
    options: [
      "When the rep directly transfers a Spanish-speaking customer to a Spanish closer",
      "When the customer only speaks Spanish and no transfer happens",
      "Whenever the opener hears Spanish on the line",
      "When the call is a language barrier with no handoff",
    ],
    correct: 0,
    explanation: "SPXFER is only for direct Spanish transfer to a closer/advisor.",
  },
  {
    id: 57,
    topic: "dosdonts",
    language: "es",
    question: "What is wrong with using SPXFER for blind Spanish routing?",
    options: [
      "It always improves Spanish reporting accuracy",
      "It is required for every Spanish speaker",
      "It can create an incorrect transfer disposition",
      "It replaces the need for transfer notes",
    ],
    correct: 2,
    explanation: "Using SPXFER for blind Spanish transfers is improper and can create process violations.",
  },
  {
    id: 58,
    topic: "dosdonts",
    language: "es",
    question: "Which disposition fits a customer who requests a later call?",
    options: [
      "XFER",
      "CALLBK",
      "DNC",
      "SPXFER",
    ],
    correct: 1,
    explanation: "CALLBK is used when the customer requests a callback.",
  },
  {
    id: 59,
    topic: "dosdonts",
    language: "es",
    question: "Which disposition fits a customer asking to be removed from the calling list?",
    options: [
      "NI",
      "DAIR",
      "BLANK",
      "DNC",
    ],
    correct: 3,
    explanation: "DNC is used when the customer asks not to be called again.",
  },
  {
    id: 60,
    topic: "dosdonts",
    language: "es",
    question: "Which behavior best avoids invalid transfers?",
    options: [
      "Verify condition, get approval, introduce properly, and wait",
      "Transfer quickly and tag XFER as soon as the line rings",
      "Promise a short wait so the customer stays connected",
      "Leave the call before the advisor confirms the handoff",
    ],
    correct: 0,
    explanation: "Clean transfers require verification, approval, proper introduction, and enough wait time.",
  }
]

export const learnCategories = [
  {
    id: 'script-en',
    icon: '📋',
    title: 'Script (English)',
    description: 'Official word for word script with transfer protocol',
    color: '#f97316',
    type: 'script',
    ref: 'en',
  },
  {
    id: 'script-es',
    icon: '📋',
    title: 'Script (Español)',
    description: 'Script oficial en español con protocolo de transferencia',
    color: '#fb923c',
    type: 'script',
    ref: 'es',
  },
  {
    id: 'objections-en',
    icon: '🛡️',
    title: 'Objections and Rebuttals',
    description: 'Approved English rebuttals for common objections',
    color: '#ea580c',
    type: 'objections',
    ref: 'en',
  },
  {
    id: 'objections-es',
    icon: '🛡️',
    title: 'Objeciones y Rebuttals',
    description: 'Objeciones comunes con respuestas aprobadas',
    color: '#c2410c',
    type: 'objections',
    ref: 'es',
  },
  {
    id: 'call-flow',
    icon: '📞',
    title: 'Call Flow',
    description: 'Call process plus transfer protocol',
    color: '#9a3412',
    type: 'callflow',
    ref: null,
  },
  {
    id: 'product-knowledge',
    icon: '📦',
    title: 'Product Knowledge',
    description: 'Coverage, exclusions, and how the product works',
    color: '#7c2d12',
    type: 'product',
    ref: null,
  },
  {
    id: 'dos-donts',
    icon: '⚠️',
    title: "Do's and Don'ts",
    description: 'Compliance rules, delivery standards, and dialer basics',
    color: '#431407',
    type: 'dosdonts',
    ref: null,
  },
  {
    id: 'dialer-guide',
    icon: '🖥️',
    title: 'Dialer Guide',
    description: 'Dispositions, pause codes, and dialer handling',
    color: '#1e40af',
    type: 'dosdonts',
    ref: null,
  },
]