import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { apiUrl, appUrl, prepareLocal, localAnonKey, sql, startBrowserRuntime, startLocalApp } from './local-runtime.mjs'

const password = prepareLocal()
const anonKey = localAnonKey()
const server = await startLocalApp(anonKey)
const browser = await startBrowserRuntime()
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, serviceWorkers: 'block' })
const requests = [], unexpected = [], errors = [], passes = []
const pass = name => { passes.push(name); console.log('PASS ' + name) }
await mkdir('studio-artifacts.local', { recursive: true })
await context.route('**/*', route => {
  const url = new URL(route.request().url())
  if (![appUrl, apiUrl].includes(url.origin)) { unexpected.push(url.origin + url.pathname); return route.abort('blockedbyclient') }
  requests.push({ method: route.request().method(), path: url.origin + url.pathname })
  return route.continue()
})
context.on('page', page => {
  page.on('response', async response => {
    if (response.url().includes('/rpc/') && response.status() >= 400) console.log('Expected/error RPC response', response.status(), response.url().split('/').pop(), (await response.text()).slice(0, 500))
  })
  page.on('pageerror', e => errors.push(e.message))
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()) })
  page.on('dialog', dialog => dialog.dismiss())
})
const runStamp = Date.now().toString()
const baseTitle = 'Browser recovery quiz ' + runStamp
const updatedTitle = 'Client A saved title ' + runStamp
const page = await context.newPage()
page.setDefaultTimeout(12000)
try {
  await page.goto(appUrl + '/signin')
  await page.getByLabel('Email address').fill('studio6@example.test')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.waitForURL('**/workspace')
  pass('real local Staff sign-in')
  await page.goto(appUrl + '/studio/create')
  const beforeCreate = sql('select count(*) from public.training_content')
  await page.getByRole('button', { name: /Quiz Interactive/ }).click()
  assert.equal(sql('select count(*) from public.training_content'), beforeCreate)
  await page.getByLabel('Title', { exact: true }).fill(baseTitle)
  await page.getByLabel('Description', { exact: false }).fill('A fully saved local browser draft.')
  await page.getByLabel('Topic Alpha', { exact: true }).check()
  await page.getByRole('button', { name: 'Continue to Audience' }).click()
  await page.getByLabel('Audience', { exact: true }).selectOption('campaign')
  await page.getByLabel('Campaign', { exact: true }).selectOption({ label: 'Campaign Alpha' })
  await page.getByLabel('Position One', { exact: true }).check()
  await page.getByRole('button', { name: 'Save draft & add questions' }).click()
  await page.waitForURL('**/studio/content/*')
  const detailUrl = page.url(), contentId = detailUrl.split('/').pop()
  assert.match(contentId, /^[0-9a-f-]{36}$/)
  await page.getByRole('button', { name: '+ Add question', exact: true }).click()
  let question = page.locator('.studio-question').nth(0)
  await question.getByLabel('Prompt', { exact: true }).fill('Choose the second answer')
  await question.getByLabel('Option 1', { exact: true }).fill('First')
  await question.getByLabel('Option 2', { exact: true }).fill('Second')
  await question.getByLabel('Correct answer: option 2', { exact: true }).check()
  await question.getByLabel('Explanation', { exact: false }).fill('The second answer is correct.')
  await page.getByRole('button', { name: '+ Add question', exact: true }).click()
  question = page.locator('.studio-question').nth(1)
  await question.getByLabel('Type', { exact: true }).selectOption('true_false')
  await question.getByLabel('Prompt', { exact: true }).fill('A true statement')
  await page.getByRole('button', { name: '+ Add question', exact: true }).click()
  question = page.locator('.studio-question').nth(2)
  await question.getByLabel('Type', { exact: true }).selectOption('text')
  await question.getByLabel('Prompt', { exact: true }).fill('Write an accepted answer')
  await question.getByLabel('Accepted answers', { exact: false }).fill('Answer\nAlternative')
  await page.getByRole('button', { name: 'Save Questions', exact: true }).click()
  await page.getByText('Questions saved.', { exact: true }).waitFor()
  pass('create with minimum contract, all three question types and section save')
  await page.locator('.studio-steps').getByRole('button', { name: /Basics/ }).click()
  await page.getByLabel('Description', { exact: true }).fill('Basics saved independently of Questions.')
  await page.getByRole('button', { name: 'Continue to Audience' }).click()
  await page.getByRole('button', { name: 'Save Basics & Audience' }).click()
  await page.getByText('Basics & Audience saved.', { exact: true }).waitFor()
  await page.locator('.studio-steps').getByRole('button', { name: /Questions/ }).click()
  await page.locator('.studio-question').first().getByLabel('Prompt', { exact: true }).fill('A changed local prompt')
  const replacementUrl = apiUrl + '/rest/v1/rpc/replace_training_questions'
  const failReplacement = route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ code: 'PGRST000', message: 'Simulated local transport failure' }) })
  await page.route(replacementUrl, failReplacement)
  await page.getByRole('button', { name: 'Save Questions', exact: true }).click()
  await page.getByText('Pulse Training is temporarily unavailable.', { exact: true }).waitFor()
  assert.equal(sql("select description from public.training_content where id='" + contentId + "'"), 'Basics saved independently of Questions.')
  assert.equal(sql("select prompt from public.training_questions where content_id='" + contentId + "' and position=1"), 'Choose the second answer')
  await page.getByText('Questions: unsaved', { exact: true }).waitFor()
  await page.unroute(replacementUrl, failReplacement)
  await page.getByRole('button', { name: 'Save Questions', exact: true }).click()
  await page.getByText('Questions saved.', { exact: true }).waitFor()
  pass('partial save failure keeps saved Basics, unsaved Questions and no optimistic database change; retry succeeds')
  await page.getByRole('button', { name: 'Move question 3 up', exact: true }).click()
  await page.getByRole('button', { name: 'Save Questions', exact: true }).click()
  await page.getByText('Questions saved.', { exact: true }).waitFor()
  await page.reload()
  await page.locator('.studio-steps').getByRole('button', { name: /Questions/ }).click()
  assert.equal(await page.locator('.studio-question').nth(1).getByLabel('Prompt', { exact: true }).inputValue(), 'Write an accepted answer')
  assert.equal(await page.locator('.studio-question').nth(1).getByLabel('Accepted answers', { exact: false }).inputValue(), 'Answer\nAlternative')
  await page.goto(appUrl + '/studio')
  await page.getByRole('link', { name: baseTitle, exact: true }).click()
  await page.locator('.studio-steps').getByRole('button', { name: /Audience/ }).click()
  assert.equal(await page.getByLabel('Campaign', { exact: true }).inputValue(), 'c3200000-0000-4000-8000-000000000001')
  assert.equal(await page.getByLabel('Position One', { exact: true }).isChecked(), true)
  pass('hard reload plus leave/reopen restores fields, audience, positions, answers and ordering')
  await page.locator('.studio-steps').getByRole('button', { name: /Basics/ }).click()
  await page.getByLabel('Title', { exact: true }).fill('Unsaved title')
  await page.getByRole('link', { name: '← Your library', exact: true }).click()
  assert.equal(page.url(), detailUrl)
  await page.getByLabel('Title', { exact: true }).fill(baseTitle)
  pass('unsaved navigation warning can keep local edits')
  const second = await context.newPage()
  await second.goto(detailUrl)
  await second.getByLabel('Title', { exact: true }).waitFor()
  await page.getByLabel('Title', { exact: true }).fill(updatedTitle)
  await page.getByRole('button', { name: 'Continue to Audience' }).click()
  await page.getByRole('button', { name: 'Save Basics & Audience' }).click()
  await page.getByText('Basics & Audience saved.', { exact: true }).waitFor()
  await second.getByLabel('Title', { exact: true }).fill('Client B stale title')
  await second.getByRole('button', { name: 'Continue to Audience' }).click()
  await second.getByRole('button', { name: 'Save Basics & Audience' }).click()
  await second.getByText('This item changed elsewhere. Reload the latest version before continuing.').waitFor()
  assert.equal(sql("select title from public.training_content where id='" + contentId + "'"), updatedTitle)
  pass('two real browser clients: stale save cannot overwrite newer content')
  await second.close()
  await page.locator('.studio-steps').getByRole('button', { name: /Review/ }).click()
  await page.getByRole('heading', { name: updatedTitle, exact: true }).last().waitFor()
  const editor = await context.newPage()
  await editor.goto(detailUrl)
  await editor.getByLabel('Description', { exact: true }).fill('Changed after review in another client.')
  await editor.getByRole('button', { name: 'Continue to Audience' }).click()
  await editor.getByRole('button', { name: 'Save Basics & Audience' }).click()
  await editor.getByText('Basics & Audience saved.', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm publish', exact: true }).click()
  await page.getByText('This item changed elsewhere. Reload the latest version before continuing.').waitFor()
  assert.equal(sql("select status from public.training_content where id='" + contentId + "'"), 'draft')
  await page.getByRole('button', { name: 'Reload latest', exact: true }).click()
  await page.getByRole('button', { name: 'Load latest review', exact: true }).click()
  await page.getByText('Changed after review in another client.', { exact: true }).waitFor()
  await editor.close()
  pass('browser publish rejects changed review and requires a fresh canonical review')
  const auditBeforePreview = sql('select count(*) from public.audit_events')
  const requestIndex = requests.length
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await page.getByRole('dialog', { name: 'Learner preview' }).waitFor()
  await page.getByRole('button', { name: 'Next question' }).click()
  await page.keyboard.press('Escape')
  assert.equal(await page.getByRole('dialog').count(), 0)
  assert.equal(sql('select count(*) from public.audit_events'), auditBeforePreview)
  assert.equal(requests.slice(requestIndex).filter(r => r.path.startsWith(apiUrl)).length, 0)
  pass('Preview and Escape: no network calls, attempts, results or audit writes')
  await page.screenshot({ path: 'studio-artifacts.local/review-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  assert.equal(sql('select count(*) from public.audit_events'), auditBeforePreview)
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm publish', exact: true }).click()
  await page.getByText('Published. Ready for your learners.', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Save Questions', exact: true }).count(), 0)
  pass('versioned publication and read-only published details')
  await page.getByRole('button', { name: 'Archive', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm archive', exact: true }).click()
  await page.getByText('Archived. Its history is kept.', { exact: true }).waitFor()
  assert.equal(sql("select count(*) from public.training_questions where content_id='" + contentId + "'"), '3')
  pass('archive preserves saved questions and shows historical detail')
  await page.goto(appUrl + '/studio')
  await page.getByLabel('Search library').fill(runStamp)
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.getByRole('button', { name: 'Archived', exact: true }).click()
  await page.getByRole('link', { name: updatedTitle, exact: true }).waitFor()
  await page.getByRole('button', { name: 'Drafts', exact: true }).click()
  await page.getByText('Your next idea starts here.', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'All', exact: true }).click()
  await page.getByRole('link', { name: updatedTitle, exact: true }).waitFor()
  pass('library status filters display correct saved state')
  for (const [name,width,height] of [['desktop',1440,1000],['tablet',820,1180],['mobile',390,844]]) {
    await page.setViewportSize({ width, height })
    await page.getByRole('heading', { name: 'Pulse Studio', exact: true }).waitFor()
    await page.waitForFunction(() => document.querySelector('.studio-load-status')?.textContent === '')
    await page.screenshot({ path: 'studio-artifacts.local/library-' + name + '.png', fullPage: true })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
    await page.goto(detailUrl)
    await page.getByRole('heading', { name: 'Quiz details' }).waitFor()
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
    await page.screenshot({ path: 'studio-artifacts.local/detail-' + name + '.png', fullPage: true })
    await page.goto(appUrl + '/studio')
  }
  pass('desktop, tablet, mobile navigation and detail fit viewport')
  await page.getByRole('heading', { name: 'Pulse Studio', exact: true }).waitFor()
  await page.keyboard.press('Tab')
  assert.equal(await page.evaluate(() => document.activeElement !== document.body), true)
  pass('keyboard focus is available')
  const paginationTitle = 'Pagination ' + runStamp
  sql("select set_config('request.jwt.claim.sub','a3200000-0000-4000-8000-000000000006',false); select id from generate_series(1,27) n cross join lateral public.create_training_content_draft('quiz','" + paginationTitle + " item ' || n,null,'en',array['23200000-0000-4000-8000-000000000001'::uuid],'global',null,null,'{}');")
  await page.getByLabel('Search library').fill(paginationTitle)
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.studio-card').length === 24)
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await page.getByText('Page 2', { exact: true }).waitFor()
  await page.waitForFunction(() => document.querySelectorAll('.studio-card').length === 3)
  await page.getByRole('button', { name: 'Drafts', exact: true }).click()
  await page.getByText('Page 1', { exact: true }).waitFor()
  await page.waitForFunction(() => document.querySelectorAll('.studio-card').length === 24)
  await page.getByRole('button', { name: 'Published', exact: true }).click()
  await page.getByText('Your next idea starts here.', { exact: true }).waitFor()
  pass('27-item real library: second page retained, status applied before pagination, explicit search')
  await page.getByRole('button', { name: 'All', exact: true }).click()
  const libraryUrl = apiUrl + '/rest/v1/rpc/list_studio_content'
  let releaseOld
  let oldResponseHeld
  const held = new Promise(resolve => { oldResponseHeld = resolve })
  const delayed = async route => {
    if (route.request().postDataJSON().requested_search === 'absent ' + runStamp) {
      const response = await route.fetch()
      oldResponseHeld()
      await new Promise(resolve => { releaseOld = resolve })
      await route.fulfill({ response })
    } else await route.continue()
  }
  await page.route(libraryUrl, delayed)
  await page.getByLabel('Search library').fill('absent ' + runStamp)
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await held
  await page.getByLabel('Search library').fill(paginationTitle)
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.studio-card').length === 24 && document.querySelector('.studio-load-status')?.textContent === '')
  releaseOld()
  await page.waitForTimeout(250)
  assert.equal(await page.locator('.studio-card').count(), 24)
  await page.unroute(libraryUrl, delayed)
  pass('late prior search response cannot replace current library results')
  for (const [actor, scope, label] of [[5, 'team', 'Team North'], [1, 'campaign', 'Campaign Alpha']]) {
    await page.getByRole('button', { name: 'Sign out', exact: true }).click()
    await page.waitForURL('**/signin')
    await page.getByLabel('Email address').fill('studio' + actor + '@example.test')
    await page.getByLabel('Password', { exact: true }).fill(password)
    await page.getByRole('button', { name: 'Sign in', exact: true }).click()
    await page.waitForURL('**/workspace')
    await page.goto(appUrl + '/studio')
    await page.getByRole('link', { name: '+ Create', exact: true }).click()
    await page.getByRole('button', { name: /Assessment Check knowledge/ }).click()
    await page.getByLabel('Title', { exact: true }).fill('Scoped assessment ' + actor + ' ' + runStamp)
    await page.getByLabel('Topic Beta', { exact: true }).check()
    await page.getByRole('button', { name: 'Continue to Audience' }).click()
    assert.equal(await page.getByLabel('Audience', { exact: true }).locator('option[value="global"]').count(), 0)
    await page.getByLabel('Audience', { exact: true }).selectOption(scope)
    await page.getByLabel(scope === 'team' ? 'Team' : 'Campaign', { exact: true }).selectOption({ label })
    const forbidden = scope === 'team' ? 'Team South' : 'Campaign Beta'
    assert.equal(await page.getByRole('option', { name: forbidden, exact: true }).count(), 0)
    await page.getByRole('button', { name: 'Save draft & add questions' }).click()
    await page.waitForURL('**/studio/content/*')
    await page.getByRole('button', { name: '+ Add question', exact: true }).click()
    await page.locator('.studio-question').getByLabel('Type', { exact: true }).selectOption('true_false')
    await page.getByLabel('Prompt', { exact: true }).fill('Scoped assessment question')
    await page.getByRole('button', { name: 'Save Questions', exact: true }).click()
    await page.getByText('Questions saved.', { exact: true }).waitFor()
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
    await page.screenshot({ path: 'studio-artifacts.local/editor-mobile-' + scope + '.png', fullPage: true })
    await page.getByRole('button', { name: 'Review', exact: true }).click()
    await page.getByRole('heading', { name: 'One last look.', exact: true }).waitFor()
    assert.equal(await page.getByRole('button', { name: 'Publish', exact: true }).count(), 0)
    pass(scope + '-scoped Staff creates Assessment, unavailable audiences and Publish omitted, mobile editor fits')
  }
  assert.deepEqual(unexpected, [])
  assert.equal(requests.some(r => /\/rest\/v1\/training_/.test(r.path)), false)
  assert.equal(requests.some(r => /start_training_attempt|complete_training_attempt|get_go_practice_content/.test(r.path)), false)
  // Expected 40001 returns an HTTP 409 and may be logged by Chrome; no unexpected errors accepted.
  assert.deepEqual(errors.filter(e => !/409 \((Conflict|training draft changed; refresh before saving|reviewed content changed)\)|503 \(Service Unavailable\)/.test(e)), [])
  pass('network allowlist: local only, protected Training RPCs only, no learner mutations')
  console.log(JSON.stringify({ browserChecks: passes.length, localRequestCount: requests.length, destinations: [...new Set(requests.map(r => new URL(r.path).origin))], rpcPaths: [...new Set(requests.filter(r => r.path.includes('/rpc/')).map(r => r.path))] }, null, 2))
} catch (error) {
  await page.screenshot({ path: 'studio-artifacts.local/failure.png', fullPage: true }).catch(() => {})
  console.error('Browser certification failed:', error.message)
  for (const openPage of context.pages()) console.error('Visible text:', openPage.url(), (await openPage.locator('body').innerText().catch(() => '')).slice(0,3000))
  console.error('Console:', errors)
  process.exitCode = 1
} finally {
  await browser.close()
  server.kill()
}
